### PR TITLE
TF2 Instance Segmentation model tutorial

### PR DESCRIPTION
**Pull request by itrushkin**
CVS-114811

### CODE REVIEW

**Comment by eaidova** [comment]
@itrushkin probably we need to add mention of notebook and model in directory readme, now it contains only info about faster rcnn
https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/120-tensorflow-object-detection-to-openvino/README.md

**Comment by itrushkin** [comment]
<p>I have listed all of the available output tensors that the model returns. Below is an explanation of which tensors are needed for our case.</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1298/discussion/#comment-1715317764'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by eaidova** [comment]
<p>I understand, from user experience perspective, there is too much info, where easy to lost attention on important things, so I just ask reformat it for grouping and highlighting which outputs you plan to use from this large amount to focus on most important context</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1298/discussion/#comment-1715317764'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by itrushkin** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1298/discussion/#comment-1715317709'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by itrushkin** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1298/discussion/#comment-1715317733'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by itrushkin** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1298/discussion/#comment-1715317745'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by itrushkin** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1298/discussion/#comment-1715317791'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by itrushkin** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1298/discussion/#comment-1715317818'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by itrushkin** [comment]
> @itrushkin probably we need to add mention of notebook and model in directory readme, now it contains only info about faster rcnn
https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/120-tensorflow-object-detection-to-openvino/README.md
Thank you! Done.

**Comment by itrushkin** [comment]
<p>Corrected the level of sections.</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1298/discussion/#comment-1715532670'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by eaidova — APPROVED** [review]

**Comment by itrushkin** [comment]
<p>Removed the unused outputs.</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1298/discussion/#comment-1715317764'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
