### PR TITLE
Create README.md for U^2-Net demo notebook

### PR DESCRIPTION
**Pull request by helena-intel**
Basic README. We should expand this, but at the moment there is no README for this notebook and we should at least give some indication what the notebook does.

### CODE REVIEW

**Comment by helena-intel** [comment]
According to our settings all CI checks need to pass, but we disabled this for markdown-only commits, so the CI will not run for this commit.

**Comment by raymondlo84** [comment]
That's a great addition. I still want to see some sort of 'gallery' mode at the front page so we can discover what's new or what's inside these notebooks from the front page.

**Comment by ryanloney** [comment]
> That's a great addition. I still want to see some sort of 'gallery' mode at the front page so we can discover what's new or what's inside these notebooks from the front page.

Do you have any suggestions on how to implement this idea? Make a GIF that is updated manually? Or some more scalable approach?

**Review by ryanloney — APPROVED** [review]
Looks good. Thank you for adding it. Where are the images hosted?

**Comment by helena-intel** [comment]
> Where are the images hosted?
I pasted them from the clipboard and github made these githubusercontent links. I kind of like it for these non-essential images, but I could also add it them to the repo.

**Pull request merged**
