### PR TITLE
Add jina-clip notebook

### PR DESCRIPTION
**Pull request by sbalandi**
CVS-145251

### CODE REVIEW

**Comment by eaidova** [comment]
@sbalandi can we focus on separated representation of text encoder and image encoder (convert it as 2 models) in this notebook instead of one common model?

The main advantage of jina-clip that it's suitable not only for text  to image matching, but also support comparing text embeddings in comparision with clip models itself, so having them as separated models may be more universal, so I think we should emphasis this

**Comment by sbalandi** [comment]
<p>updated</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2157/discussion/#comment-2202019047'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sbalandi** [comment]
> View / edit / reply to [this conversation](https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2157/discussion/#comment-2202019073) on ReviewNB
> 
> _eaidova commented on 2024-07-02T06:12:12Z_ ----------------------------------------------------------------
> 
> text-to-image usually means generation of images by text description, probably in this description you mean text-to-image-retrieval. From other part of description I read several times, but can not understand how it differ from previous example?
> 
> Probably you need to make accent on passing text and image simultaneously and preprocessing them outside model

removed here, leaved it only in description, where it was from original source

**Comment by sbalandi** [comment]
<p>It is used in gradio example </p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2157/discussion/#comment-2205226000'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sbalandi** [comment]
<p>fixed by calling directly text_model/vision_model , please, check again</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2157/discussion/#comment-2205497518'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sbalandi** [comment]
<p>added %%skip not $to_quantize.value and int8_text/vision_model_path are moved to separate cells </p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2157/discussion/#comment-2205226021'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sbalandi** [comment]
<p>added</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2157/discussion/#comment-2205226045'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sbalandi** [comment]
<p>fp16&nbsp; by default, added checkbox to manage it </p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2157/discussion/#comment-2205226060'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by eaidova — APPROVED** [review]

**Comment by sbalandi** [comment]
<p>moved</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2157/discussion/#comment-2208714887'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sbalandi** [comment]
<p>clarifications removed </p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2157/discussion/#comment-2208714871'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
