### PR TITLE
Add in jupyterlab-git plugin

### PR DESCRIPTION
**Pull request by Xaenalt**
Should check that this doesn't break dependencies if you've got different versions than what thoth-station uses, but other than that this should be all you need I think

### CODE REVIEW

**Comment by ryanloney** [comment]
@Xaenalt the build failed, we will need to look into it more but if you want to see what happened: https://github.com/openvinotoolkit/openvino_notebooks/pull/268/checks

**Comment by Xaenalt** [comment]
Huh, weird, something about supervisord there, checking my other build to be sure

**Comment by bosbes** [comment]
Thanks for the contribution! I don't know if this is what causes the test to fail, but I notice in https://github.com/openvinotoolkit/openvino_notebooks/pull/268/files that Pipfile is changed, but not Pipfile.lock - that will cause issues.

**Comment by helena-intel** [comment]
Thanks for the contribution! I don't know if this causes the test to fail but I notice in https://github.com/openvinotoolkit/openvino_notebooks/pull/268/files that Pipfile is changed and Pipfile.lock is not. That will cause problems.

**Comment by Xaenalt** [comment]
Ok, figured out the issue, Pipfile.lock has a checksum, and it's being difficult on my system, should have the PR cleaned up soonish xD

**Comment by helena-intel** [comment]
> Ok, figured out the issue, Pipfile.lock has a checksum, and it's being difficult on my system, should have the PR cleaned up soonish xD

Aah! Thanks @Xaenalt that is useful to know. If it keeps being difficult I can of course also add this change next week. I imagine it must be annoying to make a tiny quick PR and then struggle with CI failures.

**Comment by Xaenalt** [comment]
I have no idea how it computes the hash, but ideally this one should do it

**Comment by Xaenalt** [comment]
If this doesn't do it, then I officially have no clue how they compute that hash xD

**Comment by Xaenalt** [comment]
Alright, moment of truth

**Comment by helena-intel** [comment]
> Alright, moment of truth

Totally worked it seems! Thank you for your persistence! So do I understand correctly that you manually had to update this hash? I'm now worried that I will have this same issue next time I want to update this file :-) 

Also wondering if you need  this version of jupyterlab-git, or if we can upgrade it in a future build if necessary for compatibility/security reasons.

**Review by helena-intel — APPROVED** [review]
Thank you!

**Pull request merged**
