### PR TITLE
[GSoC] Prerequisite task: ESPNet Notebook

### PR DESCRIPTION
**Pull request by Nouran-Muhammad**
This my pull request to add ESPNet notebook as a prerequisite task.
The notebook runs and converts ESPNet-C (encoder) version.
i tried working on ESPNet version (encoder+decoder), but there is a problem that prevented the conversion of the model to ONNX format. It arises from a problem from the source/authors code itself and need to be changed in ESPNet's source code.

### CODE REVIEW

**Comment by Nouran-Muhammad** [comment]
@adrianboguszewski , the code check states that ReadME file is not found although it exists in the folder 236-espnet.
What should i do?

**Comment by adrianboguszewski** [comment]
Thank you for your contribution. Before we do the review please do the self-check first (tick the item when it's done):
- [ ] each function is described by docstrings and type hints
- [ ] notebook contains explicit descriptions and explanatory diagrams
- [ ] the notebook doesn't use any data (image, video, etc.) that is not CC4.0 licensed 
- [ ] there is a README.md file in consistent style (look at other notebooks)
- [ ] the notebook is added to the main README
- [ ] there are no grammar, punctuation or typo issues (use any free tool for that e.g. Grammarly)
- [ ] there are no committed files besides notebook and readme (please use images or videos from data dir)
- [ ] your PR doesn't change any other notebooks
- [ ] all CI checks passed

**Comment by adrianboguszewski** [comment]
> @adrianboguszewski , the code check states that ReadME file is not found although it exists in the folder 236-espnet and there are cancelled checks What should i do?

It's saying you haven't added your notebook to the main readme file. See the list above.

**Comment by Nouran-Muhammad** [comment]
> 

i just want to make sure what do you mean by type hints for function
is this what you mean: def func(x:int, y:int) -> int:
or just adding comments ?

**Comment by Nouran-Muhammad** [comment]
@adrianboguszewski 
I accidentally made a mistake in the last pull request and the files got missed up. Can you please close the pull request and can i make another new one?

**Comment by adrianboguszewski** [comment]
@Nouran-Muhammad, please do it yourself :)

**Pull request closed without merging**
