### PR TITLE
GPU support in the notebook image

### PR DESCRIPTION
**Pull request by dtrawins**

### CODE REVIEW

**Review by ryanloney — APPROVED** [review]

**Comment by ryanloney** [comment]
@eaidova this is needed for integration with Red Hat products. Can you do quick check for any concerns?

**Comment by eaidova** [comment]
@ryanloney for me, everything looks good, but we need to understand why ci docker testing is failed... (maybe it is not connected with these changes, but anyway)

**Comment by adrianboguszewski** [comment]
@dtrawins is this still WIP?

**Review by eaidova — APPROVED** [review]

**Comment by dtrawins** [comment]
Tests are concluded so I'm removing WIP note. It should be ready to merge if you accept a bit bigger image size with GPU drivers.

**Comment by eaidova** [comment]
@dtrawins thank you

**Pull request merged**
