### PR TITLE
225: add VAE encoder conversion

### PR DESCRIPTION
**Pull request by eaidova**

### CODE REVIEW

**Comment by raymondlo84** [comment]
there was a typo here?

        def forward(self, image):
            return e.encode(image).latent_dist.sample()

e?? 

-->

        def forward(self, image):
            return self.vae.encode(image).latent_dist.sample()

**Comment by raymondlo84** [comment]
We should change the "CPU" -> "AUTO" as well.

**Comment by raymondlo84** [comment]
https://mpost.io/best-100-stable-diffusion-prompts-the-most-beautiful-ai-text-to-image-prompts/

Also, we may wanna try a more interesting prompt? I think the current example is cool, but not cool enough :)

**Comment by eaidova** [comment]
> there was a typo here?
> 
> ```
>     def forward(self, image):
>         return e.encode(image).latent_dist.sample()
> ```
> 
> e??
> 
> -->
> 
> ```
>     def forward(self, image):
>         return self.vae.encode(image).latent_dist.sample()
> ```

yes, thanks for note, fixed

**Comment by eaidova** [comment]
> We should change the "CPU" -> "AUTO" as well.

changed

**Comment by eaidova** [comment]
> https://mpost.io/best-100-stable-diffusion-prompts-the-most-beautiful-ai-text-to-image-prompts/
> 
> Also, we may wanna try a more interesting prompt? I think the current example is cool, but not cool enough :)

please select what you wish, I'll update result

**Comment by raymondlo84** [comment]
image

Any idea on this? 

https://github.com/bes-dev/stable_diffusion.openvino

https://huggingface.co/raymondlo84/stable-diffusion-v1-4-openvino-fp16

I get this when I run it with our converted models.

 python demo.py --prompt "Street-art painting of Emilia Clarke in style of Banksy, photorealism" --model raymondlo84/stable-diffusion-v1-4-openvino-fp16

**Comment by eaidova** [comment]
probably, I need to align input and output names used in demo

**Comment by raymondlo84** [comment]
Awesome, and if this works, we can provide others the model and ask the other repos to either update the instructions or change the repos, or update the demo code. etc...

https://huggingface.co/raymondlo84/stable-diffusion-v1-4-openvino-fp16/tree/main

**Comment by eaidova** [comment]
@raymondlo84 does it planned to use only for text to image or other scenarios too?
I have some difference in how encoder was converted, so possibly if it is planned to use I need to update the conversion function

**Comment by raymondlo84** [comment]
> @raymondlo84 does it planned to use only for text to image or other scenarios too? I have some difference in how encoder was converted, so possibly if it is planned to use I need to update the conversion function

I like better code for long run. I think this is one of the most asked questions (how to convert) and so let's make it good?

**Comment by raymondlo84** [comment]
input_names=['input_ids'],  # model input name for onnx representation
                output_names=['last_hidden_state', 'pooler_out'],  # model 

Also, this is the issue right? We hard coding these names... Is there a better way?

**Comment by eaidova** [comment]
> > @raymondlo84 does it planned to use only for text to image or other scenarios too? I have some difference in how encoder was converted, so possibly if it is planned to use I need to update the conversion function
> 
> I like better code for long run. I think this is one of the most asked questions (how to convert) and so let's make it good?

I updated model input names and encoder part, please reconvert models

**Comment by eaidova** [comment]
> ```
>             input_names=['input_ids'],  # model input name for onnx representation
>             output_names=['last_hidden_state', 'pooler_out'],  # model 
> ```
> 
> Also, this is the issue right? We hard coding these names... Is there a better way?

if we do not hardcode them, they will be assigned default from model, usually it is just set of numbers, which can be different from run to run, so it is better just align names with used in demo (in our case we do not use names at all, so no difference)

**Comment by raymondlo84** [comment]
> > ```
> >             input_names=['input_ids'],  # model input name for onnx representation
> >             output_names=['last_hidden_state', 'pooler_out'],  # model 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also, this is the issue right? We hard coding these names... Is there a better way?
> 
> if we do not hardcode them, they will be assigned default from model, usually it is just set of numbers, which can be different from run to run, so it is better just align names with used in demo (in our case we do not use names at all, so no difference)

oh interesting. that's why we do the property and listing the model info... like dump info etc

**Comment by raymondlo84** [comment]
> > > @raymondlo84 does it planned to use only for text to image or other scenarios too? I have some difference in how encoder was converted, so possibly if it is planned to use I need to update the conversion function
> > 
> > 
> > I like better code for long run. I think this is one of the most asked questions (how to convert) and so let's make it good?
> 
> I updated model input names and encoder part, please reconvert models

let me update and let you know... EH... gonna do the whole upload again... D:

**Comment by raymondlo84** [comment]
oh, it only updated the xml file :D that's so cool

**Comment by raymondlo84** [comment]
almost there... now the UNET :

**Comment by raymondlo84** [comment]
image

**Comment by raymondlo84** [comment]
Ok, I think I forgot to delete the UNET folder... that's why. Let me fix it.

**Comment by raymondlo84** [comment]
> > almost there... now the UNET :
> 
> are you sure that you remove directory unet before running conversion? Looks like you still use previous onnx model. in notebook code, I have the same input name

smart smart smart smart ...

**Comment by raymondlo84** [comment]
image

**Comment by raymondlo84** [comment]
The results looks off, but well~ :D it ran! 

output

**Comment by raymondlo84** [comment]
Street-art painting of Emilia Clarke in style of Banksy, photorealism (if we run this as our prompt, we get a bit of a crazy result too).

I think now the next step is to do a side by side compare of the demo code! :)

**Comment by eaidova** [comment]
> The results looks off, but well~ :D it ran!
> 
> output

we use fine-tuned version openjorney, while in repo used original sd (due to legal issues), but I have it from initial experiments, we can align models

**Comment by raymondlo84** [comment]
> we use fine-tuned version openjorney, while in repo used original sd (due to legal issues), but I have it from initial experiments, we can align models

=D awesome!

**Comment by raymondlo84** [comment]
https://github.com/bes-dev/stable_diffusion.openvino/tree/master 

feel free to test it too, here is the prompt I used.

python demo.py --prompt "Street-art painting of Emilia Clarke in style of Banksy, photorealism" --model raymondlo84/stable-diffusion-v1-4-openvino-fp16

**Comment by eaidova** [comment]
another reason why you get different result, is the seed for the random generator. as I can  see, it is not pinned in demo if not provided, just used it fully randomly

**Comment by raymondlo84** [comment]
got it. also, we need bigger steps like 20+ or the result will look horrible.

Can we cross check the demo btw? The results always look like a shadow, and it seems the weight or similar functions are off

**Comment by raymondlo84** [comment]
50
image
20
image
10
image

**Comment by raymondlo84** [comment]
output

and ran it again with the seed, and the 'grey' out may have to do with how to scale/weight in the model flow.

**Comment by eaidova** [comment]
it is very sad that demo uses too old diffusers lib :( At least, it makes it incompatible with new models like sd 2.0, our notebook is more friendly to that. As well, as some more convenient converted model (before alignment, I reduces pre/postprocessing code and align it with original implementation)

**Comment by raymondlo84** [comment]
> it is very sad that demo uses too old diffusers lib :( At least, it makes it incompatible with new models like sd 2.0, our notebook is more friendly to that. As well, as some more convenient converted model (before alignment, I reduces pre/postprocessing code and align it with original implementation)

Let's build a v2 version of that repos then. :) We'll follow up on this again.

**Comment by eaidova** [comment]
I still trying download model from hf hub, I have some suspicious why quality is poor in demo setup, trying to verify it

**Comment by eaidova** [comment]
output
 My assamptiomn was correct, I n eed update vae_decoder export (Hope it is the last change :))

**Comment by raymondlo84** [comment]
> I n eed update vae_decoder export (Hope it is the last change :))

Also, we shall update the prompt to show a beautiful pic too =) You can pick your favour one :) and then we can update our readme (the main page) one.

**Comment by eaidova** [comment]
I think some landscape will be excellent 
result

**Comment by eaidova** [comment]
@raymondlo84 please reexport vae_decoder according the last notebook version. Now it can work in both demo and notebook with the same quality

**Review by adrianboguszewski — COMMENTED** [review]
I deleted old models and it dies every time at this step:
image

**Comment by eaidova** [comment]
<p>fixed</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/805/discussion/#comment-1415739314'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by eaidova** [comment]
> I deleted old models and it dies every time at this step
probably it is due to storing models in memory after mo.convert_model, I remove this step, please try again

**Comment by adrianboguszewski** [comment]
> > I deleted old models and it dies every time at this step
> 
> probably it is due to storing models in memory after mo.convert_model, I remove this step, please try again

Still the same. My 32GB of RAM is too little. This is not good. I don't expect an average user would have more

**Comment by adrianboguszewski** [comment]
I will try once again in the next week

**Comment by raymondlo84** [comment]
neat. I was reading the decoder export code yesterday night too! :D I saw some random code there, and now it got cleaned up 📦 

Testing it now and will post my results next.

**Comment by raymondlo84** [comment]
WOW IT WORKED!! 
output
image
And that's LOT AND LOT faster... like 6.6it/s!! D: vs 1.x...!!
image
image

```
python demo.py --prompt "Street-art painting of Emilia Clarke in style of Banksy, photorealism" --model raymondlo84/stable-diffusion-v1-4-openvino-fp16
```
output

Nice, and all we need to do now is to provide the new repos and no other code changes. :)

**Pull request merged**
