### PR TITLE
407-pedestrian-counting

### PR DESCRIPTION
**Pull request by KirigiriSuzumiya**
It's embarrassing to see my work duplicated by others, but I still want to submit my work. My pedestrian tracking and counting is based on **paddlepaddle** model and **ocsort tracker**.

### CODE REVIEW

**Comment by OpenVINO-dev-contest** [comment]
> It's embarrassing to see my work duplicated by others, but I still want to submit my work. My pedestrian tracking and counting is based on **paddlepaddle** model and **ocsort tracker**.

Hi @KirigiriSuzumiya thanks for your contribution. no worry, for education purpose, I think we can put 2 notebook instances under 407, one for Paddle model and ocsort, and another for Open Model Zoo and DeepSORT. 

@zhuo-yoyowz what's your opinion ?

**Comment by eaidova** [comment]
> Hi @KirigiriSuzumiya thanks for your contribution. no worry, for education purpose, I think we can put 2 notebook instances under 407, one for Paddle model and ocsort, and another for Open Model Zoo and DeepSORT. just like what we have in [301](https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/301-tensorflow-training-openvino)
> 
> @zhuo-yoyowz @eaidova @adrianboguszewski what's your opinion ?

sure, I do not see the problem to have different realizations

**Comment by adrianboguszewski** [comment]
> > It's embarrassing to see my work duplicated by others, but I still want to submit my work. My pedestrian tracking and counting is based on **paddlepaddle** model and **ocsort tracker**.
> 
> Hi @KirigiriSuzumiya thanks for your contribution. no worry, for education purpose, I think we can put 2 notebook instances under 407, one for Paddle model and ocsort, and another for Open Model Zoo and DeepSORT. just like what we have in [301](https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/301-tensorflow-training-openvino)
> 
> @zhuo-yoyowz @eaidova @adrianboguszewski what's your opinion ?

I tested both of them and in my opinion, they are close enough to be combined into one notebook

**Comment by paularamo** [comment]
The two notebooks have good things. We can combine those into one. Remember that we need to add an educational tone and sources for developers in the code. We need to combine the strengths of the two versions.

**Pull request closed without merging**
