### PR TITLE
Split yolo v8 optimization notebooks to 3 separate

### PR DESCRIPTION
**Pull request by sbalandi**
colab object detection - https://colab.research.google.com/github/sbalandi/openvino_notebooks/blob/yolov/notebooks/230-yolov8-optimization/230-yolov8-object-detection.ipynb
instance segmentation - https://colab.research.google.com/github/sbalandi/openvino_notebooks/blob/yolov/notebooks/230-yolov8-optimization/230-yolov8-instance-segmentation.ipyn
kypoint detection - https://colab.research.google.com/github/sbalandi/openvino_notebooks/blob/yolov/notebooks/230-yolov8-optimization/230-yolov8-keypoint-detection.ipynb

Task:
- *CVS-111529*

### CODE REVIEW

**Comment by eaidova** [comment]
@sbalandi there are some typos in notebooks ( inferece, pipline and so on, could you please check results of spell_check job and fix?

**Comment by sbalandi** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1258/discussion/#comment-1689376021'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by eaidova** [comment]
<p>I think it can be postponed and done in request with migration on new api</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1258/discussion/#comment-1694749526'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sbalandi** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1258/discussion/#comment-1695039798'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sbalandi** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1258/discussion/#comment-1695039826'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sbalandi** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1258/discussion/#comment-1695039841'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sbalandi** [comment]
<p>changed</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1258/discussion/#comment-1696740693'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sbalandi** [comment]
<p>removed from all notebooks </p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1258/discussion/#comment-1696740687'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sbalandi** [comment]
spell check will be fixed here after https://github.com/openvinotoolkit/openvino_notebooks/pull/1277 is merged

**Comment by sbalandi** [comment]
this pr for develop branch will be closed and same pr for main branch: https://github.com/openvinotoolkit/openvino_notebooks/pull/1281

**Comment by sbalandi** [comment]
<p>fixed, but moved to another pr https://github.com/openvinotoolkit/openvino_notebooks/pull/1281</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1258/discussion/#comment-1697245254'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request closed without merging**
