### PR TITLE
Add SAM2 notebook

### PR DESCRIPTION
**Pull request by sbalandi**
CVS-149017

### CODE REVIEW

**Comment by sbalandi** [comment]
fixed a lot of fails with height_res_features/high_res_fetures

**Comment by eaidova** [comment]
@sbalandi according to sam2 package install, they support only python3.10+, https://github.com/facebookresearch/segment-anything-2/blob/main/setup.py#L144

Please do not forget to disable python3.8 and python3.9 in ci ignore list and add warning about that in notebook

**Comment by eaidova** [comment]
<p>is it needed? I suppose instead debug=True should be added</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2333/discussion/#comment-2364688431'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by aleksandr-mokrov** [comment]
<p>debug=True would be better</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2333/discussion/#comment-2364688431'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by eaidova — APPROVED** [review]

**Pull request merged**
