### PR TITLE
Mentor side task

### PR DESCRIPTION
**Pull request by pyther-hub**
I have done some extra tasks given by the mentor

### CODE REVIEW

**Comment by adrianboguszewski** [comment]
@pyther-hub, who is the mentor who gave you this task?

**Comment by pyther-hub** [comment]
@AlexKoff88 gave me this task

**Comment by adrianboguszewski** [comment]
@pyther-hub, thank you for the contribution. However, this task will be implemented as part of the GSoC project this year.

**Comment by pyther-hub** [comment]
sir is it possible for you to add this as a new notebook because I did quantisation aware training also in this one, I can do the required changes if you want

**Comment by adrianboguszewski** [comment]
Please focus first on #952. Then we can restore this :)

**Comment by pyther-hub** [comment]
okay sir no issue, I have completed the work there if possible please have a look to it

**Pull request closed without merging**
