### PR TITLE
Move 110-ct-scan-live-inference on AsyncInferQueue

### PR DESCRIPTION
**Pull request by sbalandi**

### CODE REVIEW

**Comment by adrianboguszewski** [comment]
@sbalandi, please also remove all unnecessary imports and code from .py files

**Comment by sbalandi** [comment]
> @sbalandi, please also remove all unnecessary imports and code from .py files

I remove imports and fix other ci issues related to 110-ct-scan-live-inference, but I can not remove code from .py now, because show_live_inference is included to another 110 tutorials. should I remove the function in other tutorials too ?

**Comment by adrianboguszewski** [comment]
> > @sbalandi, please also remove all unnecessary imports and code from .py files
> 
> I remove imports and fix other ci issues related to 110-ct-scan-live-inference, but I can not remove code from .py now, because show_live_inference is included to another 110 tutorials. should I remove the function in other tutorials too ?

Just remove any unused code. If still used, leave it.

**Comment by sbalandi** [comment]
> > > @sbalandi, please also remove all unnecessary imports and code from .py files
> > 
> > 
> > I remove imports and fix other ci issues related to 110-ct-scan-live-inference, but I can not remove code from .py now, because show_live_inference is included to another 110 tutorials. should I remove the function in other tutorials too ?
> 
> Just remove any unused code. If still used, leave it.

okay, that is done

**Review by eaidova — APPROVED** [review]

**Pull request merged**
