### PR TITLE
Update Stable Diffusion v2 README.md (typos)

### PR DESCRIPTION
**Pull request by raymondlo84**

### CODE REVIEW

**Review by eaidova — APPROVED** [review]

**Comment by raymondlo84** [comment]
Please update the new readme, typos are still in the new readme

**Comment by raymondlo84** [comment]
Also, we need to update the GIF. The old one has a glitch at the end. :)

**Comment by raymondlo84** [comment]
ezgif-4-d16bc51d7f

**Comment by raymondlo84** [comment]
result

**Comment by raymondlo84** [comment]
https://github.com/openvinotoolkit/openvino_notebooks/pull/975 Added these changes to the new PR.

**Comment by raymondlo84** [comment]
ezgif-4-998ec37e29
shorter and sweeter version.

**Pull request merged**
