### PR TITLE
Stable audio model example

### PR DESCRIPTION
**Pull request by aleksandr-mokrov**
CVS-144663

### CODE REVIEW

**Comment by aleksandr-mokrov** [comment]
<p>Renamed</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2188/discussion/#comment-2222990265'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by aleksandr-mokrov** [comment]
<p>Weight Compression is added. But only with mode=CompressWeightsMode.INT8_SYM it generates good results.</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2188/discussion/#comment-2222990291'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by aleksandr-mokrov** [comment]
<p>Extended</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2188/discussion/#comment-2222990315'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by aleksandr-mokrov** [comment]
<p><a href="https://github.com/openvinotoolkit/openvino/blob/master/tools/ovc/openvino/tools/ovc/moc_frontend/pytorch_frontend_utils.py#L137C5-L137C23" target="_blank">https://github.com/openvinotoolkit/openvino/blob/master/tools/ovc/openvino/tools/ovc/moc_frontend/pytorch_frontend_utils.py#L137C5-L137C23</a></p><p>Non informational outputs was removed</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2188/discussion/#comment-2222990336'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by eaidova — APPROVED** [review]

**Pull request merged**
