### PR TITLE
Paularamo/fixing sam51

### PR DESCRIPTION
**Pull request by paularamo**
Testing Code_Checker in both notebooks, fixing metadata in the original one and adding new images (From External contributor) in the Fiftyone version.

### CODE REVIEW

**Comment by adrianboguszewski** [comment]
@paularamo also check your line endings because you modified the entire treon file

**Comment by paularamo** [comment]
> 

That was done by the code format tool in Jupyter Lab.

**Comment by paularamo** [comment]
> View / edit / reply to [this conversation](https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1077/discussion/#comment-1562568391) on ReviewNB
> 
> _adrianboguszewski commented on 2023-05-25T09:18:29Z_ ----------------------------------------------------------------
> 
> Line #30.            point_embedding = (
> these external round brackets don't change anything - the effect is exactly the same as without them. Same for line 36

That was done by the code format tool in Jupyter Lab.

**Comment by paularamo** [comment]
@jacobmarks Please take a look at the CI result. As I mentioned in my email, it looks like is a memory issue. So we suggest running it locally, see how much memory it takes and compare to the limit we have on GitHub CI.

**Comment by paularamo** [comment]
> @jacobmarks Please take a look at the CI result. As I mentioned in my email, it looks like is a memory issue. So we suggest running it locally, see how much memory it takes and compare to the limit we have on GitHub CI.

@jacobmarks, we have found a critical compatibility issue. We'll need to put this notebook down until you and your team can work on a solution that's the best way to merge that again in our repo.

gradio(starlette==0.20.4) --> Fiftyone
gradio(starlette>=0.26.1,<0.27.0) ---> in our repo.

Thanks for your help in improving this for devs.

**Pull request closed without merging**
