### PR TITLE
[GSoC] 238-Photo2Cartoon

### PR DESCRIPTION
**Pull request by sususama**
# Convert Photo to cartoon ONNX Model to OpenVINO™ IR

[Photo2Cartoon results](https://github.com/sususama/Test1/blob/master/AOP/1678799732564.png)

This tutorial explains how to convert the [photo2cartoon](https://github.com/minivision-ai/photo2cartoon) ONNX Model to OpenVINO™ IR

## Notebook Contents

This tutorial demonstrates the running results of photo2cartoon and converts it from ONNX model to the IR model used by OpenVION.

The tutorial consists of the following steps:
- Prepare the environment required for program operation 
- Downlad pre-train model
- Validate original model
- Convert ONNX model to openVINO IR
- Verify model inference

## Installation Instructions

If you have not installed all required dependencies, follow the [Installation Guide](../../README.md).

### CODE REVIEW

**Comment by sususama** [comment]
Hi, @eaidova 
Can you approve the audit now? I have corrected the mistakes reported in the previous audit.
Thanks.

**Comment by sususama** [comment]
Hi, @eaidova 
Sorry, due to my negligence, I didn't notice that I need to update README.md while updating notebook. Because I don't know how to put the picture in https://user-images.githubusercontent.com Above, I placed the images from README.md in one of my unused GitHub repositories. Please use the checker again to check my code. I'm sorry to trouble you.

**Comment by adrianboguszewski** [comment]
Thank you for your contribution. Before we do the review please do the self-check first (tick the item when it's done):
- [ ] each function is described by docstrings and type hints
- [ ] notebook contains explicit descriptions and explanatory diagrams
- [ ] there is a README.md file in consistent style (look at other notebooks)
- [ ] the notebook is added to the main README and notebooks/README files
- [ ] there are no grammar, interpunctions or typo issues (use any free tool for that e.g. Grammarly)
- [ ] there are no committed files besides notebook and readme (please use images or videos from data dir)
- [ ] all CI checks passed

We will review only if all the above items are checked.

**Comment by adrianboguszewski** [comment]
To put the picture under that URL, upload it to this PR and then copy the link.

**Comment by sususama** [comment]
> Hi, @adrianboguszewski I have almost completed all self-check, except for the penultimate item, because the model for this project is not on GitHub. Can you give me some tips or suggestions? I can use the model without uploading files to Github.

Now, I have a preliminary idea. I can put the project Fork of photo2cartoon into my warehouse, and then directly upload the model in the corresponding directory. I'm trying to do it now.

**Comment by sususama** [comment]
Hi, I have solved all my previous problems. But I don't know how there are so many checks.And now the error is due to an error in the download of the dependency on the mac system.

**Comment by sususama** [comment]
Hello, @adrianboguszewski , @eaidova . In the current inspection, there is not a problem with my code. Due to my error, I will not know what version has been mixed into my code. Can I restart a PR and resubmit my application now.

**Pull request closed without merging**
