### PR TITLE
[GSoC] 238-Photo2Cartoon

### PR DESCRIPTION
**Pull request by sususama**
# Convert Photo to cartoon ONNX Model to OpenVINO™ IR

[Photo2Cartoon results](https://github.com/sususama/Test1/blob/master/AOP/1678799732564.png)

This tutorial explains how to convert the [photo2cartoon](https://github.com/minivision-ai/photo2cartoon) ONNX Model to OpenVINO™ IR

## Notebook Contents

This tutorial demonstrates the running results of photo2cartoon and converts it from ONNX model to the IR model used by OpenVION.

The tutorial consists of the following steps:
- Prepare the environment required for program operation 
- Downlad pre-train model
- Validate original model
- Convert ONNX model to openVINO IR
- Verify model inference

## Installation Instructions

If you have not installed all required dependencies, follow the [Installation Guide](../../README.md).

### CODE REVIEW

**Comment by adrianboguszewski** [comment]
Thank you for your contribution. Before we do the review please do the self-check first (tick the item when it's done):
- [ ] each function is described by docstrings and type hints
- [ ] notebook contains explicit descriptions and explanatory diagrams
- [ ] the notebook doesn't use any data (image, video, etc.) that is not CC4.0 licensed 
- [ ] there is a README.md file in consistent style (look at other notebooks)
- [ ] the notebook is added to the main README and notebooks/README files
- [ ] there are no grammar, interpunctions or typo issues (use any free tool for that e.g. Grammarly)
- [ ] there are no committed files besides notebook and readme (please use images or videos from data dir)
- [ ] your PR doesn't change any other notebooks
- [ ] all CI checks passed

**Comment by sususama** [comment]
> Thank you for your contribution. Before we do the review please do the self-check first (tick the item when it's done):
> 
> * [x]  each function is described by docstrings and type hints
> * [x]  notebook contains explicit descriptions and explanatory diagrams
> * [x]  the notebook doesn't use any data (image, video, etc.) that is not CC4.0 licensed
> * [x]  there is a README.md file in consistent style (look at other notebooks)
> * [x]  the notebook is added to the main README and notebooks/README files
> * [x]  there are no grammar, interpunctions or typo issues (use any free tool for that e.g. Grammarly)
> * [x]  there are no committed files besides notebook and readme (please use images or videos from data dir)
> * [x]  your PR doesn't change any other notebooks
> * [x]  all CI checks passed

I have confirmed that all of the above tasks have been completed.

**Comment by sususama** [comment]
> Thank you, we will review it when we have some resources. Please note we're reviewing PRs in FIFO style. Note: The PR must be opened before April 4th, it doesn't have to be reviewed or merged.

In fact, the result of this code is a bit problematic. There is a certain gap between the picture it generates and the picture generated by the original model on the pytorch platform. It may be a problem with some of my code, so please delay my PR merge. I will fix this as soon as possible.

**Comment by adrianboguszewski** [comment]
Sure. The result should be the same unless you change the model precision.

**Comment by sususama** [comment]
Hi, @adrianboguszewski 
I have some questions for GSoC application. I want to apply for the project that **Showcase performance of PyTorch Image Models (timm) with OpenVINO.**
1. In my understanding, what this project needs to do is similar to this PR, is that true?
2. Can I offer some input of my own on this project? I want to compare the specific running speed of the same model on the Pytorch platform and the OpenVINO platform under the same hardware.
3. Does 'properly benchmarking under the various settings' mean a comparison of models trained under different hyperparameters?

**Comment by sususama** [comment]
Would you mind answering these questions for me? If you can't, please leave a message and I would be very grateful.

**Comment by adrianboguszewski** [comment]
@sususama, the mentor for this task is @AlexKoff88 and he is the right person to ask these questions :)

**Comment by sususama** [comment]
Thank you for your work. I will contact mentor as soon as possible.

**Pull request closed without merging**
