### PR TITLE
[GSoC] Added segmenter notebook

### PR DESCRIPTION
**Pull request by blaz-r**
This PR is part of the prerequisite task for GSoC'23.
It demonstrates how to convert and use [Segmenter](https://github.com/rstrudel/segmenter) model for semantic segmentation with OpenVINO.

I selected the name 236 as there is already PR open with number 235 #845.

One thing that I should mention is that I did not include an evaluation with ADE20K, because as far as I understand the [terms of use](https://groups.csail.mit.edu/vision/datasets/ADE20K/terms/) don't allow commercial use. I do have code for that prepared as well, but the other thing is that it's also quite a big dataset and inference isn't that fast. Is the current implementation of basic validation of inference enough in this case?

### CODE REVIEW

**Comment by Warlord-K** [comment]
Hi @blaz-r , I think that there is a 5 second timeout for each cell execution,and other notebooks bypass it because the models are downloaded beforehand,which is automatically done by the test,maybe look at some other notebooks and how they are downloading the files. It could be unrelated but I thought it might help.

**Comment by blaz-r** [comment]
Hi @Warlord-K 
Thanks for your advice. I am loading the weights the same way as in YOLOv7 notebook, but I think that in my case the file is a bit bigger. It only fails at one MacOS version so I'm not entirely sure, but I guess that I could try moving download to separate cell.

**Comment by eaidova** [comment]
@blaz-r thank you for your submission, code looks good. Yes, it is no need to download and test model quality on full dataset (in majority cases, we use this step only if model optimization provided to compare accuracy of floating point model and quantized.

The only small notice, could you please submit notebook with stored output? For users, it will be nice to see output result in notebook directly

**Comment by blaz-r** [comment]
@eaidova thank you for the feedback. I now also included output in the notebook as requested.

**Comment by blaz-r** [comment]
Thank you for your feedback @eaidova.
>@blaz-r could you please also include benchmarking for model inference?

As I asked in the original message, I'm not sure what data to benchmark on. ADE20K, on which the model is trained, is under a license that says it can't be used commercially. 
Or do you want me to use OpenVINO [Benchmark Tool](https://docs.openvino.ai/latest/openvino_inference_engine_tools_benchmark_tool_README.html) that is used in YOLOv7 notebook? This wouldn't require ADE20K dataset, so I can do that.

>Also I do not think that it is good idea to preserve dynamic batch during onnx conversion as this feature is not demonstrated in notebook. Can this model be exported with static input shape?

Yes, the model can be exported with static input. Dynamic batch size is there because the inference function from the original repository, when evaluated with ADE20K, can sometimes produce batch sizes different from those statically assigned. The dynamic shape works in OpenVINO as well, but if I'm not using ADE20K, then it's not needed and I can remove it.

**Comment by eaidova** [comment]
I mean performance benchmarking using benchmark tool, it does not require ade20k

**Comment by blaz-r** [comment]
@eaidova Thank you for the clarification. I will add that and change the input to static shape.

**Comment by blaz-r** [comment]
It seems like nbval is failing in a cell where weights are downloaded on MacOS. I'm not sure why it sometimes fails in test, but sometimes it works. It does always work on Linux and Windows though. The weights are 26MB, and that is the smallest model available.

**Comment by eaidova** [comment]
> It seems like nbval is failing in a cell where weights are downloaded on MacOS. I'm not sure why it sometimes fails in test, but sometimes it works. It does always work on Linux and Windows though. The weights are 26MB, and that is the smallest model available.

do not worry for now, it required to download models in test infra before notebook test started, I think it can be done later, after finishing main review

**Comment by adrianboguszewski** [comment]
Thank you for your contribution. Before we do the review please do the self-check first (tick the item when it's done):
- [ ] each function is described by docstrings and type hints
- [ ] notebook contains explicit descriptions and explanatory diagrams
- [ ] there is a README.md file in consistent style (look at other notebooks)
- [ ] the notebook is added to the main README and notebooks/README files
- [ ] there are no grammar, interpunctions or typo issues (use any free tool for that e.g. Grammarly)
- [ ] there are no committed files besides notebook and readme (please use images or videos from data dir)
- [ ] all CI checks passed

We will review only if all the above items are checked.

**Comment by blaz-r** [comment]
* [x]  each function is described by docstrings and type hints
* [x]  notebook contains explicit descriptions and explanatory diagrams
* [x]  the notebook doesn't use any data (image, video, etc.) that is not CC4.0 licensed
* [x]  there is a README.md file in consistent style (look at other notebooks)
* [x]  the notebook is added to the main README and notebooks/README files
* [x]  there are no grammar, interpunctions or typo issues (use any free tool for that e.g. Grammarly)
* [x]  there are no committed files besides notebook and readme (please use images or videos from data dir)
* [ ]  all CI checks passed

**Comment by adrianboguszewski** [comment]
Let's rebase and see the result

**Comment by adrianboguszewski** [comment]
Probably you assume the CI and the environment are deterministic, but they're not ;) There are updates on some dependencies from time to time, broken links, connection issues, and so on. But no worries, if not related to your notebook.

**Comment by blaz-r** [comment]
Code_check us failing due to unreachable links on binder in readme after the latest merge with fix for some notebooks.

**Comment by blaz-r** [comment]
> * [x]   each function is described by docstrings and type hints
> 
>     * [x]   notebook contains explicit descriptions and explanatory diagrams
> 
>     * [x]   the notebook doesn't use any data (image, video, etc.) that is not CC4.0 licensed
> 
>     * [x]   there is a README.md file in consistent style (look at other notebooks)
> 
>     * [x]   the notebook is added to the main README and notebooks/README files
> 
>     * [x]   there are no grammar, interpunctions or typo issues (use any free tool for that e.g. Grammarly)
> 
>     * [x]   there are no committed files besides notebook and readme (please use images or videos from data dir)
> 
>     * [x]   all CI checks passed
> 
> 
> Last tick is almost done, but docker fails on notebook 227 that is not changed in this PR.

Everything is done now.

**Comment by adrianboguszewski** [comment]
Thank you, we will review it when we have some resources. Please note we're reviewing PRs in FIFO style. 
Note: The PR must be opened before April 4th, it doesn't have to be reviewed or merged.

**Comment by blaz-r** [comment]
Thanks for update. I have submitted proposal with PR link, so that's fine. Looking forward to PR review 😊

**Comment by blaz-r** [comment]
<p>Changed html to markdown and added credits in jupyter and readme.</p><p> </p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/902/discussion/#comment-1506971531'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by blaz-r** [comment]
<p>This is now fixed by adding segmenter directory to path. I used this as given example notebook for yolov7 does this, so it might also be a good idea to adjust it there as well.</p><p> </p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/902/discussion/#comment-1506971566'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by blaz-r** [comment]
<p>This is now fixed by using correct mmseg version.</p><p> </p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/902/discussion/#comment-1506971589'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by blaz-r** [comment]
<p>Fixed.</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/902/discussion/#comment-1506996496'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by blaz-r** [comment]
@adrianboguszewski thank you for all comments. Everything should be fixed now.

**Review by adrianboguszewski — APPROVED** [review]
I'm going to approve that, but please also replace HTML image with markdown in the readme file.

**Comment by blaz-r** [comment]
@adrianboguszewski thank you for review and all the feedback :). I replaced HTML for diagram but forgot to replace the one for image so I will do that now.

**Comment by blaz-r** [comment]
Hello, I'm just writing to check if there is any update on review?

**Comment by blaz-r** [comment]
Thank you for the update ☺️

**Comment by eaidova** [comment]
@blaz-r final review finished. Please fix minor comment regarding dependencies install and move notebook to 204 place. After that it can be merged. Thank you for your great work!

**Comment by blaz-r** [comment]
<p>Added quotes, command also has -q.</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/902/discussion/#comment-1523429676'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by blaz-r** [comment]
@eaidova fixed dependencies and moved to 204. It is now ready when all the tests run.

**Review by eaidova — APPROVED** [review]

**Pull request merged**
