### PR TITLE
Added quantization to LCM notebook

### PR DESCRIPTION
**Pull request by l-bat**
Add post-training optimization support by NNCF for UNet model from [263-latent-consistency-models-image-generation.ipynb](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/263-latent-consistency-models-image-generation/263-latent-consistency-models-image-generation.ipynb)
Pipeline performance speed up: 1.307

### CODE REVIEW

**Comment by l-bat** [comment]
@MaximProshin, @eaidova, @nikita-savelyevv please take a look

**Comment by l-bat** [comment]
<p>I use 10&nbsp;samples. 128 data files relates to internal dataset files.</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1411/discussion/#comment-1787298439'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by l-bat** [comment]
<p>Added </p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1411/discussion/#comment-1787326895'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by l-bat** [comment]
<p>I use default nncf version from <a href="https://github.com/openvinotoolkit/openvino_notebooks/blob/main/requirements.txt#L4" target="_blank">https://github.com/openvinotoolkit/openvino_notebooks/blob/main/requirements.txt#L4</a></p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1411/discussion/#comment-1787326933'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nikita-savelyevv** [comment]
> I use default nncf version from https://github.com/openvinotoolkit/openvino_notebooks/blob/main/requirements.txt#L4
> 
> [View entire conversation](https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1411/discussion/#comment-1787326933) on ReviewNB

Please see https://github.com/openvinotoolkit/openvino_notebooks/pull/1363#discussion_r1356490623

**Review by MaximProshin — COMMENTED** [review]
LGTM
I was able to run it on my Win laptop and got 1.5x vs FP16. Generated pictures are also ok compared to FP16. Imo, it's not easy to quickly compare pictures from INT8 and FP16 - is it possible to have it a part of the demo and allow the user to select the precision directly there?

**Comment by l-bat** [comment]
<p>Added</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1411/discussion/#comment-1787326933'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by l-bat** [comment]
<p>Added comparison&nbsp;</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1411/discussion/#comment-1787326975'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by eaidova — APPROVED** [review]

**Review by MaximProshin — APPROVED** [review]

**Review by nikita-savelyevv — APPROVED** [review]

**Comment by ngaloppo** [comment]
<p>the <code>size</code> argument is never used.  </p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1411/discussion/#comment-1787298439'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by l-bat** [comment]
<p>Added</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1411/discussion/#comment-1788793961'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by l-bat** [comment]
<p>thanks! Removed <code>size</code></p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1411/discussion/#comment-1787298439'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
