### PR TITLE
[GSoC] Added 250-NanoDet tutorial notebook

### PR DESCRIPTION
**Pull request by sahilpmehra**
This PR is part of the prerequisite task for GSoC'23.
It demonstrates how to convert and use [NanoDet](https://github.com/RangiLyu/nanodet) model with OpenVINO.

I selected the name 250 so that there is no issue with other Pull Requests. Can be changed later.

### CODE REVIEW

**Comment by adrianboguszewski** [comment]
Thank you for your contribution. Before we do the review please do the self-check first (copy the list and tick the item when it's done):
- [ ] each function is described by docstrings and type hints
- [ ] notebook contains explicit descriptions and explanatory diagrams
- [ ] the notebook doesn't use any data (image, video, etc.) that is not CC4.0 licensed 
- [ ] there is a README.md file in consistent style (look at other notebooks)
- [ ] the notebook is added to the main README
- [ ] there are no grammar, punctuation or typo issues (use any free tool for that e.g. Grammarly)
- [ ] there are no committed files besides notebook and readme (please use images or videos from data dir)
- [ ] your PR doesn't change any other notebooks
- [ ] all CI checks passed

**Comment by raymondlo84** [comment]
image

We need to recreate this diagram.

**Comment by raymondlo84** [comment]
import sys
from pathlib import Path
sys.path.append("../utils")
from notebook_utils import download_file
     

# Clone nanodet repo
if not Path('nanodet').exists():
    !git clone https://github.com/RangiLyu/nanodet
%cd nanodet
     
/content/drive/My Drive/openvino_notebooks-main/notebooks/nanodet/nanodet

!pip install - r requirements.txt

     

!python setup.py develop

     

!pip install onnxruntime


Can we compact them together better? and we may need to version lock them.

**Comment by raymondlo84** [comment]
MODEL_LINK = "https://drive.google.com/u/0/uc?id=1ZkYucuLusJrCb_i63Lid0kYyyLvEiGN3&export=download"
This can be problematic. We may need alternative way to host these files.

**Comment by sahilpmehra** [comment]
Thank you @adrianboguszewski for your response. 

- [ ] each function is described by docstrings and type hints
- [ ]  notebook contains explicit descriptions and explanatory diagrams
- [ ]  the notebook doesn't use any data (image, video, etc.) that is not CC4.0 licensed
- [ ]  there is a README.md file in consistent style (look at other notebooks)
- [ ]  the notebook is added to the main README
- [ ]  there are no grammar, punctuation or typo issues (use any free tool for that e.g. Grammarly)
- [ ]  there are no committed files besides notebook and readme (please use images or videos from data dir)
- [ ]  your PR doesn't change any other notebooks
- [ ]  all CI checks passed

**Comment by sahilpmehra** [comment]
> image
> 
> We need to recreate this diagram.

Hi @raymondlo84 Thanks for your review. Do you mean I should recreate the diagram and use that image instead of the current image being used?

**Comment by sahilpmehra** [comment]
> import sys from pathlib import Path sys.path.append("../utils") from notebook_utils import download_file
> 
> # Clone nanodet repo
> if not Path('nanodet').exists(): !git clone https://github.com/RangiLyu/nanodet %cd nanodet
> 
> /content/drive/My Drive/openvino_notebooks-main/notebooks/nanodet/nanodet
> 
> !pip install - r requirements.txt
> 
> !python setup.py develop
> 
> !pip install onnxruntime
> 
> Can we compact them together better? and we may need to version lock them.

Yes, I will compact them together and version lock onnxruntime. Not sure if I can version lock the others as it is part of the nanodet repository but I checked that they have version locked it in the requirements file currently.

**Comment by sahilpmehra** [comment]
> MODEL_LINK = "https://drive.google.com/u/0/uc?id=1ZkYucuLusJrCb_i63Lid0kYyyLvEiGN3&export=download" This can be problematic. We may need alternative way to host these files.

Looking for alternate ways for this. Will get back to you soon. Would be grateful if you could suggest some ideas as well.

**Comment by adrianboguszewski** [comment]
Closing due to inactivity in the last 2 weeks

**Pull request closed without merging**
