### PR TITLE
Update OpenVINO notebooks for Ultralytics YOLOv8.1 release

### PR DESCRIPTION
**Pull request by glenn-jocher**
@adrianboguszewski this PR updates all 3 OpenVINO notebooks for [YOLOv8.1](https://github.com/ultralytics/ultralytics) usage. YOLO8.1 is our most recent form January 10th, 2024: https://github.com/ultralytics/ultralytics/releases/tag/v8.1.0

The main changes are:

- Update notebook installation steps from `ultralytics==8.0.143` to `ultralytics>=8.1`.
- Update import structure to reflect newer simplified usage with removal of `ultralytics.yolo` module, i.e. `ultralytics.yolo.utils` is now `ultralytics.utils`, and the same for other imports that used to be under `ultralytics.yolo`. This modification reflects an emphasis on cross-model compatibility for the `ultralytics` package.
- Minor README updates.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
I'm seeing an error in the CI. It looks like the previous usage of the validator class needs updating. The error is on the Segment notebook but it's likely that all 3 need updating. I'll investigate further.

```diff
- seg_validator = seg_model.ValidatorClass(args=args)
+ seg_validator = seg_model.task_map[seg_model.task]['validator'](args=args)
```

**Comment by adrianboguszewski** [comment]
@andrei-kochin @eaidova This is PR updating our yolov8 notebooks. I'm leaving it to you

**Comment by itrushkin** [comment]
Hey @glenn-jocher, thank you for your contribution to OpenVINO Notebooks! With those changes in place, all three notebooks can now be removed from `.ci/ignore_pip_conflicts.txt`.

**Comment by adrianboguszewski** [comment]
@glenn-jocher notebook 122 could be updated also

**Comment by raymondlo84** [comment]
wow! Super cool. Keeping my eye on this.

**Comment by eaidova** [comment]
> I'm seeing an error in the CI. It looks like the previous usage of the validator class needs updating. The error is on the Segment notebook but it's likely that all 3 need updating. I'll investigate further.
> 
> ```diff
> - seg_validator = seg_model.ValidatorClass(args=args)
> + seg_validator = seg_model.task_map[seg_model.task]['validator'](args=args)
> ```

Hi @glenn-jocher, what the current status? do you need help from our sidet?

**Comment by glenn-jocher** [comment]
@raymondlo84 @eaidova hi there! I submitted this a bit prematurely, so I've now marked it as a draft to indicate it's not ready for review just yet. I'll try to dedicate some more time to this soon, thank you for reaching out!

**Comment by aleksandr-mokrov** [comment]
Hi @glenn-jocher! Do you have plans to complete this PR? We can update the notebooks by ourselves if you have difficulties to find time on it.

**Comment by glenn-jocher** [comment]
@aleksandr-mokrov apologies, I haven't had time to complete this. If you'd like to create a new PR for these updates that would be awesome. 

We've had a burst of OpenVINO updates on the Ultralytics repo lately, so we now support version 2024.0 with batched inference optimizations and smart selection between OpenVINO `LATENCY` and `CUMULATIVE_THROUGHPUT` modes:

- https://github.com/ultralytics/ultralytics/pull/8834
- https://github.com/ultralytics/ultralytics/pull/8726
- https://github.com/ultralytics/ultralytics/pull/8417

**Pull request closed without merging**
