### PR TITLE
[Recipe]update meter reader recipe

### PR DESCRIPTION
**Pull request by OpenVINO-dev-contest**

### CODE REVIEW

**Comment by OpenVINO-dev-contest** [comment]
@zhuo-yoyowz FYI

**Review by zhuo-yoyowz — APPROVED** [review]

**Comment by OpenVINO-dev-contest** [comment]
@adrianboguszewski Could you help to merge ?

**Comment by OpenVINO-dev-contest** [comment]
@adrianboguszewski Could you help to merge ?

**Comment by adrianboguszewski** [comment]
Sure :)

**Pull request merged**
