### PR TITLE
[GSOC] Add 241 Ultra-lightweight face detection notebook

### PR DESCRIPTION
**Pull request by JacketChenlll**

### CODE REVIEW

**Comment by adrianboguszewski** [comment]
Thank you for your contribution. Before we do the review please do the self-check first (copy the list and tick the item when it's done):
- [ ] each function is described by docstrings and type hints
- [ ] notebook contains explicit descriptions and explanatory diagrams
- [ ] the notebook doesn't use any data (image, video, etc.) that is not CC4.0 licensed 
- [ ] there is a README.md file in consistent style (look at other notebooks)
- [ ] the notebook is added to the main README
- [ ] there are no grammar, punctuation or typo issues (use any free tool for that e.g. Grammarly)
- [ ] there are no committed files besides notebook and readme (please use images or videos from data dir)
- [ ] your PR doesn't change any other notebooks
- [ ] all CI checks passed

**Comment by raymondlo84** [comment]
We should not upload the binary if possible.

keyboard_arrow_down
notebooks/241-ultraface-detection/models/version-RFB-320.xml
keyboard_arrow_down
notebooks/241-ultraface-detection/models/version-RFB-640.bin
keyboard_arrow_down
notebooks/241-ultraface-detection/models/version-RFB-640.xml

**Comment by JacketChenlll** [comment]
> 

thanks，I will update my submit later

**Comment by adrianboguszewski** [comment]
Closing due to inactivity in the last 2 weeks

**Pull request closed without merging**
