### PR TITLE
Notebook to run inference for LCM using Optimum Intel with OpenVINO 

### PR DESCRIPTION
**Pull request by DimaPastushenkov**
Notebook allows to run inference with the standard Diffusers pipeline and the Optimum Intel pipeline on CPU and GPU

### CODE REVIEW

**Comment by raymondlo84** [comment]
Who else shall we add as reviewer?

**Comment by eaidova** [comment]
@DimaPastushenkov thanks, important general notes:
1. we do not store images in repository and prefer downloading or using them as links on external resources if they should be embedded in markdown
2. we avoid naming Core object as ie in code as ie is associated with old API 1.0 and for new users it brings more questions then answers
3. We prefer install optimum without openvino extra as in one day our required version and optimum intel may be different
4. What good for specific training section or blog post not always good for regular users. Notebook has assumption that both CPU and GPU exists in user setup  but on practice it is not always true (user may have GPU from different manufacturer or multiple cards, or even his platform does not support GPU inference via openvino (I mean ARM)), instead of loading on specific devices, we prefer to allow user choice it by device selection widget. Please rewrite using it or at least make GPU part optional (skip execution if there is no GPU in available devices).

**Comment by DimaPastushenkov** [comment]
@eaidova, I have made all requested changes and set PR to "Ready for review".
One image is still stored in the repo, but I've significantly reduced its size. Please let me know if it is acceptable.

**Comment by eaidova** [comment]
@DimaPastushenkov my suggestion to replace it with
https://github.com/openvinotoolkit/openvino_notebooks/assets/29454499/ede014d1-64cd-4692-9f6f-59fd66083807

(it is the same image, just uploaded on github in different way, for doing that it irequired to put inage into any comment filed on github, it will be automatically uploaded and in preview mode you can see link on you image)

**Comment by DimaPastushenkov** [comment]
> 4. What good for specific training section or blog post not always good for regular users. Notebook has assumption that both CPU and GPU exists in user setup  but on practice it is not always true (user may have GPU from different manufacturer or multiple cards, or even his platform does not support GPU inference via openvino (I mean ARM)), instead of loading on specific devices, we prefer to allow user choice it by device selection widget. Please rewrite using it or at least make GPU part optional (skip execution if there is no GPU in available devices).
@eaidova , I have made GPU part optional. Please let me know whether it is better to make device selectable by device selection widget and will rework the notebook accordingly.

**Comment by DimaPastushenkov** [comment]
> View / edit / reply to [this conversation](https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1696/discussion/#comment-1959427305) on ReviewNB
> 
> _aleksandr-mokrov commented on 2024-02-22T13:10:40Z_ ----------------------------------------------------------------
> 
> Line #1.    from optimum.intel import OVLatentConsistencyModelPipeline
> It causes error:
> 
> No module named 'onnx'
> If onnx is installed:
> 
> KeyError: 'clip-text-model is not supported yet with the onnx backend. Only [] are supported. If you want to support onnx please propose a PR or open up an issue.'


@aleksandr-mokrov , I cannot reproduce the issue in Linux and in Windows. Could you please let me know which environment do you use? 
This is the output, which I get:
Using framework PyTorch: 2.1.0+cpu
Using framework PyTorch: 2.1.0+cpu
Using framework PyTorch: 2.1.0+cpu
Using framework PyTorch: 2.1.0+cpu
Compiling the vae_decoder to CPU ...
Compiling the unet to CPU ...
Compiling the text_encoder to CPU ...
Compiling the vae_encoder to CPU ...

**Comment by aleksandr-mokrov** [comment]
> > View / edit / reply to [this conversation](https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1696/discussion/#comment-1959427305) on ReviewNB
> > _aleksandr-mokrov commented on 2024-02-22T13:10:40Z_ ----------------------------------------------------------------
> > Line #1.    from optimum.intel import OVLatentConsistencyModelPipeline
> > It causes error:
> > No module named 'onnx'
> > If onnx is installed:
> > KeyError: 'clip-text-model is not supported yet with the onnx backend. Only [] are supported. If you want to support onnx please propose a PR or open up an issue.'
> 
> @aleksandr-mokrov , I cannot reproduce the issue in Linux and in Windows. Could you please let me know which environment do you use? This is the output, which I get: Using framework PyTorch: 2.1.0+cpu Using framework PyTorch: 2.1.0+cpu Using framework PyTorch: 2.1.0+cpu Using framework PyTorch: 2.1.0+cpu Compiling the vae_decoder to CPU ... Compiling the unet to CPU ... Compiling the text_encoder to CPU ... Compiling the vae_encoder to CPU ...

I created new empty virtual environment, all packages are installed by running this notebook. Ubuntu, python3.10, torch==2.2.1+cpu

**Comment by DimaPastushenkov** [comment]
> > > View / edit / reply to [this conversation](https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1696/discussion/#comment-1959427305) on ReviewNB
> > > _aleksandr-mokrov commented on 2024-02-22T13:10:40Z_ ----------------------------------------------------------------
> > > Line #1.    from optimum.intel import OVLatentConsistencyModelPipeline
> > > It causes error:
> > > No module named 'onnx'
> > > If onnx is installed:
> > > KeyError: 'clip-text-model is not supported yet with the onnx backend. Only [] are supported. If you want to support onnx please propose a PR or open up an issue.'
> > 
> > 
> > @aleksandr-mokrov , I cannot reproduce the issue in Linux and in Windows. Could you please let me know which environment do you use? This is the output, which I get: Using framework PyTorch: 2.1.0+cpu Using framework PyTorch: 2.1.0+cpu Using framework PyTorch: 2.1.0+cpu Using framework PyTorch: 2.1.0+cpu Compiling the vae_decoder to CPU ... Compiling the unet to CPU ... Compiling the text_encoder to CPU ... Compiling the vae_encoder to CPU ...
> 
> I created new empty virtual environment, all packages are installed by running this notebook. Ubuntu, python3.10, torch==2.2.1+cpu
> 
> After installing onnx and restarting the kernel it works. Add onnx for installation


I have added onnx to the dependencies

**Review by aleksandr-mokrov — APPROVED** [review]

**Review by eaidova — APPROVED** [review]

**Pull request merged**
