### PR TITLE
movienet model optimization using MONODEPTH OPENVINO IR

### PR DESCRIPTION
**Pull request by sharvesh642**
In the attached notebook I have optimized the `movienet` model by first loading it, then converting it into OPENVINO IR and then optimizing it.
Later I applied Monodepth Optimization to the example video in order to get a more accurate result.

### CODE REVIEW

**Comment by adrianboguszewski** [comment]
Thank you for your contribution. Before we do the review please do the self-check first (copy the list and tick the item when it's done):
- [ ] each function is described by docstrings and type hints
- [ ] notebook contains explicit descriptions and explanatory diagrams
- [ ] the notebook doesn't use any data (image, video, etc.) that is not CC4.0 licensed 
- [ ] there is a README.md file in consistent style (look at other notebooks)
- [ ] the notebook is added to the main README
- [ ] there are no grammar, punctuation or typo issues (use any free tool for that e.g. Grammarly)
- [ ] there are no committed files besides notebook and readme (please use images or videos from data dir)
- [ ] your PR doesn't change any other notebooks
- [ ] all CI checks passed

**Comment by raymondlo84** [comment]
!command -v ffmpeg >/dev/null || (apt update && apt install -y ffmpeg)

This won't work on Windows.

**Comment by raymondlo84** [comment]
It's missing significant amount of documentation, and the code is unlikely will be able to run across platforms.

**Comment by adrianboguszewski** [comment]
Closing due to inactivity in the last 2 weeks

**Pull request closed without merging**
