### PR TITLE
[GSOC]Added 204: Text Spotting - Detection & Recognition

### PR DESCRIPTION
**Pull request by sawradip**
This notebook shows how to recognize and detect text using OpenVINO Runtime.

In this notebook, we use the [Text Spotting Model](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/intel/text-spotting-0005) from [Open Model Zoo](https://github.com/openvinotoolkit/open_model_zoo/). The model is built on top of the Mask-RCNN framework with additional attention-based text recognition head.

### CODE REVIEW

**Comment by sawradip** [comment]
I want to   add `gsoc` and `new notebook` label here, but I  am not  sure how to  do that or if I have access. Waiting feedback from   maintainers.

**Comment by adrianboguszewski** [comment]
@sawradip, thank you for your contribution. It looks good at a glance. But let's wait for the official announcement of GSoC 2023 organizations (22nd February) before we proceed :)

**Comment by sawradip** [comment]
Thank you for the appreciation. I was planning to add more external text-spotting model support (Ex: mmocr) to this notebook, would that be alright? Or would that somehow break the requirement?

**Comment by eaidova** [comment]
> Thank you for the appreciation. I was planning to add more external text-spotting model support (Ex: mmocr) to this notebook, would that be alright? Or would that somehow break the requirement?

@sawradip  adding public models will be fine fitting to this year's requirements :)

**Comment by adrianboguszewski** [comment]
@sawradip, the new prerequisite task is ready. Please look at it: https://github.com/openvinotoolkit/openvino/wiki/Google-Summer-Of-Code#prerequisite-task
You are free to use any external model :)

**Comment by sawradip** [comment]
I am closing this, due to some branching fault. I will be adding this again.

**Pull request closed without merging**
