### PR TITLE
[GSoC] 239 - DeOldify

### PR DESCRIPTION
**Pull request by Dhruvanshu-Joshi**
This PR is a part of the pre-requisite task required for GSOC 2023.
I have worked on the model [DeOldify](https://github.com/jantic/DeOldify), loaded its inference using the pytorch model, converted it into a OpenVINO IR model and generated coloured result on black and white image and video input using this model.

### CODE REVIEW

**Comment by adrianboguszewski** [comment]
Thank you for your contribution. Before we do the review please do the self-check first (tick the item when it's done):
- [ ] each function is described by docstrings and type hints
- [ ] notebook contains explicit descriptions and explanatory diagrams
- [ ] the notebook doesn't use any data (image, video, etc.) that is not CC4.0 licensed 
- [ ] there is a README.md file in consistent style (look at other notebooks)
- [ ] the notebook is added to the main README
- [ ] there are no grammar, punctuation or typo issues (use any free tool for that e.g. Grammarly)
- [ ] there are no committed files besides notebook and readme (please use images or videos from data dir)
- [ ] your PR doesn't change any other notebooks
- [ ] all CI checks passed

**Comment by Dhruvanshu-Joshi** [comment]
Hey @adrianboguszewski there seems to be an issue with the test  for macos-11, 3.10. However, I tried to run this locally and everything seems fine. Can you shed some light on this issue.
Screenshot from 2023-04-03 02-08-51

**Comment by adrianboguszewski** [comment]
Yeah, sometimes there are some issues with mac packages. Unfortunately, I don't have access to macOS right now. Let's ignore them for now.

**Comment by Dhruvanshu-Joshi** [comment]
Hey @adrianboguszewski Thank You for your time. I understand that we are ignoring these errors temporarily. However, in the future if there is any work to be done on it from my end, I am glad to contribute. I would also like to work on it if this a recurring issue and needs tackling if you are ready to guide me on it.

**Comment by Dhruvanshu-Joshi** [comment]
Thank you for your contribution. Before we do the review please do the self-check first (tick the item when it's done):

- [x] each function is described by docstrings and type hints
- [x] notebook contains explicit descriptions and explanatory diagrams
- [x] the notebook doesn't use any data (image, video, etc.) that is not CC4.0 licensed
- [x] there is a README.md file in consistent style (look at other notebooks)
- [x] the notebook is added to the main README
- [x] there are no grammar, punctuation or typo issues (use any free tool for that e.g. Grammarly)
- [x] there are no committed files besides notebook and readme (please use images or videos from data dir)
- [x] your PR doesn't change any other notebooks
- [x] all CI checks passed (except for changes we are temporarily ignoring)

**Comment by adrianboguszewski** [comment]
Thank you, we will review it when we have some resources. Please note we're reviewing PRs in FIFO style. 
Note: The PR must be opened before April 4th, it doesn't have to be reviewed or merged.

**Comment by raymondlo84** [comment]
It needs a quick clean up.

core = Core()
# read converted model
image = input_type()[0]
artistic = input_type()[1]
wt_name, onnx_path, onnx_name, xml_name, bin_name = attributes(image, artistic)
model = core.read_model(xml_name)
# load model on CPU device
compiled_model = core.compile_model(model, 'CPU')
input_layer = compiled_model.input(0)
N, C, H, W = input_layer.shape
output_layer = compiled_model.output(0)
print('Model Input and Output Info')
print(f"- input shape: {input_layer.shape}")
print(f"- input precision: {input_layer.element_type}")
print(f"- output shape: {output_layer.shape}")
print(f"- output precision: {output_layer.element_type}")
image = input_type()[0]
image_filename = 'test_images/image.png'
img = cv2.imread(image_filename)
(h_orig, w_orig) = img.shape[:2]
imshow_size = (w_orig, h_orig)
input_img = pre_processing(img, W, H)
result = compiled_model([input_img])[output_layer]
coloured_img = post_processing(result[0], imshow_size)
plt.imshow(coloured_img)
plt.show()

Also, would recommend slices things up properly so it doesn't look like a smack of code sometimes. ;)

**Comment by Dhruvanshu-Joshi** [comment]
Hey @raymondlo84. Thank you for the review. I will add commits incorporating your suggestions soon. Currently in midst of final exams so might run a little late though.

**Comment by adrianboguszewski** [comment]
I'm closing this due to inactivity for a long time. Nevertheless, thank you for contributing and applying for Google Summer of Code. We encourage you to consider GSoC 2024 as well :)

**Pull request closed without merging**
