### PR TITLE
Update ultralytics notebooks

### PR DESCRIPTION
**Pull request by aleksandr-mokrov**
[CVS-135289]
[CVS-135318]
[CVS-133231]

### CODE REVIEW

**Comment by eaidova** [comment]
@aleksandr-mokrov could you please also update https://github.com/openvinotoolkit/openvino_notebooks/blob/latest/notebooks/quantizing-model-with-accuracy-control/yolov8-quantization-with-accuracy-control.ipynb

**Comment by aleksandr-mokrov** [comment]
<p>It is not required now. Changed to half=True</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1890/discussion/#comment-2044653369'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by aleksandr-mokrov** [comment]
<p>Yes, it is work in this way</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1890/discussion/#comment-2044653398'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by aleksandr-mokrov** [comment]
<p>@<a href="https://github.com/eaidova" target="_blank">eaidova</a>&nbsp;<a href="https://github.com/openvinotoolkit/openvino_notebooks/blob/latest/notebooks/quantizing-model-with-accuracy-control/yolov8-quantization-with-accuracy-control.ipynb" target="_blank">https://github.com/openvinotoolkit/openvino_notebooks/blob/latest/notebooks/quantizing-model-with-accuracy-control/yolov8-quantization-with-accuracy-control.ipynb</a>&nbsp;and&nbsp;<a href="https://github.com/openvinotoolkit/openvino_notebooks/blob/latest/notebooks/fast-segment-anything/fast-segment-anything.ipynb" target="_blank">https://github.com/openvinotoolkit/openvino_notebooks/blob/latest/notebooks/fast-segment-anything/fast-segment-anything.ipynb</a> were updated </p>

**Review by eaidova — APPROVED** [review]

**Pull request merged**
