### PR TITLE
Update Chinese version README file, README_cn.md

### PR DESCRIPTION
**Pull request by yoyowz**
Update Chinese version README file, README_cn.md

### CODE REVIEW

**Comment by raymondlo84** [comment]
Zhuo, can you please update it with the latest changes? We have two new notebooks just added this week! Thank you.

Also, does Binder works in PRC? If not we may want to take out those links.

**Review by raymondlo84 — CHANGES_REQUESTED** [review]
Please update along with the two new notebooks.

**Comment by yoyowz** [comment]
recent features/notebooks update sync

**Comment by yoyowz** [comment]
> Zhuo, can you please update it with the latest changes? We have two new notebooks just added this week! Thank you.
> 
> Also, does Binder works in PRC? If not we may want to take out those links.

Hi Ray, have updated the README_cn.md with the two new notebooks info. Please help to review. Also, as far as I've checked, the Binder link works well in PRC.

**Review by raymondlo84 — APPROVED** [review]
Great.

**Pull request merged**
