### PR TITLE
Update README.md to add description of OpenVino and reference to oneAPI-samples repo

### PR DESCRIPTION
**Pull request by jimmytwei**
Requested by Chekuri to add the following section to the top level README.md

OpenVINO™ toolkit takes advantage of the discrete GPUs using oneAPI, an open programming model for multi-architecture programming. The [oneAPI-samples](https://github.com/oneapi-src/oneAPI-samples) repository demonstrates the performance and productivity offered by oneAPI and its toolkits such as oneDNN in a multiarchitecture environment.

### CODE REVIEW

**Review by yatarkan — COMMENTED** [review]
[Spell check job](https://github.com/openvinotoolkit/openvino_notebooks/actions/runs/10268847077/job/28442629246?pr=2268) is failed.
Please refer to the [Contribution Guide - Spell Check](https://github.com/openvinotoolkit/openvino_notebooks/blob/latest/CONTRIBUTING.md#pyspelling) for information on how to fix it

**Comment by eaidova** [comment]
> [Spell check job](https://github.com/openvinotoolkit/openvino_notebooks/actions/runs/10268847077/job/28442629246?pr=2268) is failed. Please refer to the [Contribution Guide - Spell Check](https://github.com/openvinotoolkit/openvino_notebooks/blob/latest/CONTRIBUTING.md#pyspelling) for information on how to fix it

I can get more details:
@jimmytwei you need to add unknown for validation words into ignored list, contributing.md contains hint how to do that

**Comment by eaidova** [comment]
I'm not sure that it is correct place for such reference. Maybe it is better create additional section Additional Resources (https://github.com/oneapi-src/oneAPI-samples?tab=readme-ov-file#additional-resources-for-code-samples) or Other usage examples (like here https://github.com/openvinotoolkit/open_model_zoo?tab=readme-ov-file#other-usage-examples) for such references?

**Comment by jimmytwei** [comment]
@eaidova Thanks for the feedback. Are you asking about adding an additional section called `Additional Resources` in the README? Where should I add that section in the Table of Contents? Or can I place this section before the Table of Contents? I would like to get your opinion on this.

**Comment by eaidova** [comment]
@jimmytwei  I grab your chenges in my PR with additional resources section proposal https://github.com/openvinotoolkit/openvino_notebooks/pull/2293

**Pull request closed without merging**
