### PR TITLE
222-person-attributes-recognition-crossroad

### PR DESCRIPTION
**Pull request by spencergotowork**
### 222-person-attributes-recognition-crossroad

This notebook shows person attributes recognition crossroad.

image
image

### CODE REVIEW

**Comment by raymondlo84** [comment]
;) The accuracy seems a bit off?

**Comment by spencergotowork** [comment]
> ;) The accuracy seems a bit off?

Yes, the model didn't seem to support previous images very well and might require more complicated processing than using the model directly, so I replaced the clear images and changed the display. Results the following.
image

**Comment by raymondlo84** [comment]
We did a quick review today, and we think the first and most important step is to clean up all the unnecessary files before you commit any future work. For now, we will push this PR on hold. I will reach out to you directly, and closing this submission does not mean you had failed the pre-req task for GSOC. However, this is also a good starting lesson to see what it takes to make a contribution to the repository.

**Comment by raymondlo84** [comment]
image
For example, we shall never commit these cache files.

**Pull request closed without merging**
