### PR TITLE
StableCascade image generation

### PR DESCRIPTION
**Pull request by aleksandr-mokrov**
CVS-139009

### CODE REVIEW

**Comment by aleksandr-mokrov** [comment]
<p>Updated</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1979/discussion/#comment-2085044508'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by aleksandr-mokrov** [comment]
<p>Loading doesn't affect, models are replaced one by one with a larger one. But inference increase memory consumption. Added a widget with the choice to perform inference from the original model or not, skipping inference by default.</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1979/discussion/#comment-2085044529'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by aleksandr-mokrov** [comment]
<p>Changed</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1979/discussion/#comment-2085044561'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by aleksandr-mokrov** [comment]
<p>Added extra information and the separate guidance scale for the decoder pipeline was added </p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1979/discussion/#comment-2085044608'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by eaidova — APPROVED** [review]

**Comment by aleksandr-mokrov** [comment]
<p>removed</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1979/discussion/#comment-2088424705'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
