### PR TITLE
[GSoC] OPT model quantization

### PR DESCRIPTION
**Pull request by zhumakhan**
This is a part of issue #832

### CODE REVIEW

**Comment by zhumakhan** [comment]
It seem test is failing due to timeout, which is expected since OPT350m model is quite massive.

**Comment by zhumakhan** [comment]
> Thank you for your contribution. Before we do the review please do the self-check first (tick the item when it's done):
> 
>     * [x]  each function is described by docstrings and type hints
> 
>     * [x]  notebook contains explicit descriptions and explanatory diagrams
> 
>     * [x]  the notebook doesn't use any data (image, video, etc.) that is not CC4.0 licensed
> 
>     * [x]  there is a README.md file in consistent style (look at other notebooks)
> 
>     * [x]  the notebook is added to the main README
> 
>     * [x] there are no grammar, punctuation or typo issues (use any free tool for that e.g. Grammarly)
> 
>     * [x]  there are no committed files besides notebook and readme (please use images or videos from data dir)
> 
>     * [x]  your PR doesn't change any other notebooks
> 
>     * [x]  all CI checks passed
> 
> 
> We are aware of your timeouts, please check if there are no more issues.

**Comment by adrianboguszewski** [comment]
Thank you, we will review it when we have some resources. Please note we're reviewing PRs in FIFO style. 
Note: The PR must be opened before April 4th, it doesn't have to be reviewed or merged.

**Comment by adrianboguszewski** [comment]
I'm closing this due to inactivity for a long time. Nevertheless, thank you for contributing and applying for Google Summer of Code. We encourage you to consider GSoC 2024 as well :)

**Pull request closed without merging**
