### PR TITLE
Add badges

### PR DESCRIPTION
**Pull request by alexeyhorkin**
I thought it would be nice to add badges like https://github.com/openvinotoolkit/openvino in REAMDE.md

### CODE REVIEW

**Comment by alexeyhorkin** [comment]
Looks like this:
image

**Comment by helena-intel** [comment]
Thanks @alexeyhorkin I like this a lot! I'm not sure yet about the release badge - we have been talking about how to go about releases. The 0.1.0 release is old. Currently we encourage users to use the main branch - that is the version that is tested and supported. We also do not yet expose how to use the Docker image to users - but it would be good to offer that as an option and then having this badge is great.

**Review by helena-intel — APPROVED** [review]
Thanks @alexeyhorkin ! If we do decide to make proper releases we can always put the release badge back. I really like the badges.

**Review by ryanloney — APPROVED** [review]
Thanks @alexeyhorkin! These badges look nice. 

Helena - I think we should tag a 2021.4 release soon.

**Pull request merged**
