### PR TITLE
Removed notebooks 204 and 212

### PR DESCRIPTION
**Pull request by adrianboguszewski**
@helena-intel @rageshhajela16 
As you may have noticed, we have been working on expanding the range of notebooks. Eliminating duplicity in some of them. 
We're going to remove 204 and 212 notebooks from the repository's main branch, but they will remain active in the previous release branches. 

We really appreciate the effort you have put into developing your notebooks. We invite you to continue contributing with us in the continuous improvement of the notebooks. 

Notebook 204 will be covered by 213, and notebook 212 will be covered by 404. 

Thanks for your contributions.

### CODE REVIEW

**Review by eaidova — APPROVED** [review]

**Comment by raymondlo84** [comment]
We have to sync this to the tutorial (documentation) before we delete (avoid 404 issues). How do we ensure these are synchronized?

**Comment by raymondlo84** [comment]
Please also update the contribution guide on delete, renaming or reusing the indices. 

Also, in long run, we shall track any external links (inbound) to the notebooks. Lastly, not sure how but it would always nice to have a achieved bucket just in case people still want to use the older notebooks that's no longer 'supported'.

**Comment by raymondlo84** [comment]
https://docs.openvino.ai/latest/notebooks/204-named-entity-recognition-with-output.html (well, we have to remove this too?) They are cross-linked.

> > We have to sync this to the tutorial (documentation) before we delete (avoid 404 issues). How do we ensure these are synchronized?
> 
> There is no connection between tutorials (documentation) and these notebooks. This is an acyclical relationship (notebooks -> documentation)
> 
> > Please also update the contribution guide on delete, renaming or reusing the indices.
> 
> Added.
> 
> > Also, in long run, we shall track any external links (inbound) to the notebooks.
> 
> Nice idea, but how to do it right?

Not sure either, but do the best we can, like the 'documentation' is definitely linked to this. 

> 
> > Lastly, not sure how but it would always nice to have the achieved bucket (backup or the commit checkpoint) just in case people still want to use the older notebooks that's no longer 'supported'.
> 
> All of them are still available in the other branches.

Ok done.

**Comment by raymondlo84** [comment]
https://mybinder.org/v2/gh/openvinotoolkit/openvino_notebooks/HEAD?filepath=notebooks%2F204-named-entity-recognition%2F204-named-entity-recognition.ipynb

The binder will failed if we removed it.

**Comment by eaidova** [comment]
> https://mybinder.org/v2/gh/openvinotoolkit/openvino_notebooks/HEAD?filepath=notebooks%2F204-named-entity-recognition%2F204-named-entity-recognition.ipynb
> 
> The binder for example will fail if we remove it.

probably, link is incorrect, should be branch specified instead of HEAD?

**Comment by adrianboguszewski** [comment]
I talked to the documentation team. They will update the documentation after we remove them. 

Still working on some automatic solution.

**Pull request merged**
