### PR TITLE
Fix load_image call

### PR DESCRIPTION
**Pull request by aleksandr-mokrov**
CVS-159041

### CODE REVIEW

**Review by sbalandi — APPROVED** [review]

**Comment by sbalandi** [comment]
Did it work before ? If yes, shouldn't the lower version of diffusers be changed ?

**Comment by aleksandr-mokrov** [comment]
> Did it work before ? If yes, shouldn't the lower version of diffusers be changed ?

It is not because of diffusers. Recently we changed our load_image and that changes affected this function call, but it is load_image from diffusers not our.

**Comment by sbalandi** [comment]
> > Did it work before ? If yes, shouldn't the lower version of diffusers be changed ?
> 
> It is not because of diffusers. Recently we changed our load_image and that changes affected this function call, but it is load_image from diffusers not our.

if it is not our function, how could changes in ours affect it? it was used our before ?

**Comment by aleksandr-mokrov** [comment]
> > > Did it work before ? If yes, shouldn't the lower version of diffusers be changed ?
> > 
> > 
> > It is not because of diffusers. Recently we changed our load_image and that changes affected this function call, but it is load_image from diffusers not our.
> 
> if it is not our function, how could changes in ours affect it? it was used our before ?

The call of this function was changed too by mistake

**Review by andrei-kochin — APPROVED** [review]

**Pull request merged**
