### PR TITLE
update 237 with NNCF PTQ

### PR DESCRIPTION
**Pull request by OpenVINO-dev-contest**
This PR will help to improve the performance of Encoder in SAM pipeline on CPU
@AlexKoff88 Could you help to check whether the configuration of PTQ is correct to take the best performance, thanks.

### CODE REVIEW

**Comment by AlexKoff88** [comment]
cc'ed @alexsu52

**Comment by OpenVINO-dev-contest** [comment]
<p>Great thanks for your suggestion, and I have replace the dataset. I prefer create a new dataloader instead of using ultralytics library, so we don't need to install another dependency,</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1027/discussion/#comment-1527377171'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by OpenVINO-dev-contest** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1027/discussion/#comment-1527377184'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by eaidova** [comment]
<p>def transform_fn(image)</p><p>...</p><p>Parameters:</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;data_item:</p><p> </p><p>docstring and function parameters are inconsistent, please align</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1027/discussion/#comment-1527377184'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by OpenVINO-dev-contest** [comment]
<p>Since quantization on a large model is a memory consumption task, it can help user to reduce the memory usage.</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1027/discussion/#comment-1545092344'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by OpenVINO-dev-contest** [comment]
<p>Sure, i will add it later</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1027/discussion/#comment-1545092353'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by OpenVINO-dev-contest** [comment]
@eaidova @alexsu52 Could you help to do further review, thanks

**Comment by OpenVINO-dev-contest** [comment]
> View / edit / reply to [this conversation](https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1027/discussion/#comment-1550749812) on ReviewNB
> 
> _eaidova commented on 2023-05-17T05:18:58Z_ ----------------------------------------------------------------
> 
> it is difficult to compare with previous result due to different colors used, maybe we can use predefined colors and use the same for each run?
> 
> e.g. use some class for storing color map (if new index provided, generate new color, else use already predefined), however we still can be affected that prediction order changed, but I think visually it is still will be more clear

I found the order of mask generating is different between FP16 and INT8 models, so it will be difficult to track the index of color in same mapping area.

**Comment by OpenVINO-dev-contest** [comment]
> View / edit / reply to [this conversation](https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1027/discussion/#comment-1550749799) on ReviewNB
> 
> _eaidova commented on 2023-05-17T05:18:57Z_ ----------------------------------------------------------------
> 
> Line #6.            self.images_path = images_path
> still mixing
> 
> class COCOLoader(data.Dataset):
> 
>    def __init__(self, images_path):
> 
>        self.images_path = Path(mages_path)
> 
>        self.images = list(iself.mages_path.glob("*"))
> 
>    def __getitem__(self, index):
> 
>        image_path = self.images[index]
> 
>        image = cv2.imread(str(image_path))
> 
>        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
> 
>        return image

Fixed

**Comment by eaidova** [comment]
@OpenVINO-dev-contest ci failed with:

       1 import PIL
      2 
----> 3 out, colors = draw_anns(image, prediction)
      4 cv2.imwrite("result.png", out[:, :, ::-1])
      5 

ValueError: too many values to unpack (expected 2)

Could you please fix?

**Comment by OpenVINO-dev-contest** [comment]
> @OpenVINO-dev-contest ci failed with:
> 
> ```
>    1 import PIL
>   2 
> ```
> 
> ----> 3 out, colors = draw_anns(image, prediction) 4 cv2.imwrite("result.png", out[:, :, ::-1]) 5
> 
> ValueError: too many values to unpack (expected 2)
> 
> Could you please fix?

Done, but I see the kernel is killed in CI now, probably by quantization approach

**Comment by eaidova** [comment]
> > @OpenVINO-dev-contest ci failed with:
> > ```
> >    1 import PIL
> >   2 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ----> 3 out, colors = draw_anns(image, prediction) 4 cv2.imwrite("result.png", out[:, :, ::-1]) 5
> > ValueError: too many values to unpack (expected 2)
> > Could you please fix?
> 
> Done, but I see the kernel is killed in CI now, probably by quantization approach

I'll exclude it in separated PR

**Pull request merged**
