### PR TITLE
Stable Diffusion v2: Adding Demo Notebook and Diagram Adjustments

### PR DESCRIPTION
**Pull request by riacheruvu**
Detailed list of changes:

- Modified stable diffusion diagrams in 236-stable-diffusion-v2-text-to-image.ipynb and 236-stable-diffusion-v2-infinite-zoom.ipynb to have a horizontal orientation, to make it easier to read
- Added _236-stable-diffusion-v2-text-to-image-demo.ipynb_ as a short demo illustrating the capabilities of text to image for stable diffusion, along with the _implementation/_ folder containing implementations of the OVStableDiffusion pipelines from the notebooks in .py files. Developers can view 236-stable-diffusion-v2-text-to-image.ipynb for in-depth explanations compared to the demo notebook.
- Changed the README with the new diagrams and link to the new demo notebook

### CODE REVIEW

**Comment by riacheruvu** [comment]
> According to [PEP8](https://peps.python.org/pep-0008/#package-and-module-names) all python files should be short, lowercase and underscored.
> 
> Btw. what's the difference between 236-stable-diffusion-v2-text-to-image-demo.ipynb and 236-stable-diffusion-v2-text-to-image.ipynb? Why are there 2 of them?

@adrianboguszewski, thanks! I'll make the adjustment for PEP8. _236-stable-diffusion-v2-text-to-image-demo.ipynb_ is our shorter DevCON demo that is hiding the additional details of the Stable Diffusion pipeline class that the original _text-to-image_ demo contains.

**Comment by riacheruvu** [comment]
<p>Thanks, fixed with the new commit!</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1153/discussion/#comment-1602749862'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by riacheruvu** [comment]
<p>Removed the unnecessary imports.</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1153/discussion/#comment-1602749836'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by adrianboguszewski** [comment]
@riacheruvu, so please add short descriptions to these notebooks with cross-links saying e.g. "This is a shorter version of XYZ notebook without ABC and DEF. If you want to test ABC and DEF visit XYZ." and the same for the longer notebook "This is a full version, if you just want to run it quickly, open GHI."

I cannot see any changes you committed. Did you push them?

**Comment by riacheruvu** [comment]
>

**Comment by riacheruvu** [comment]
> @riacheruvu, so please add short descriptions to these notebooks with cross-links saying e.g. "This is a shorter version of XYZ notebook without ABC and DEF. If you want to test ABC and DEF visit XYZ." and the same for the longer notebook "This is a full version, if you just want to run it quickly, open GHI."
> 
> I cannot see any changes you committed. Did you push them?

Thank you, @adrianboguszewski - the changes are in there now - sorry about that!

**Pull request merged**
