### PR TITLE
Added quantization to MMS speech recognition notebook

### PR DESCRIPTION
**Pull request by nikita-savelyevv**
Added quantization with about 1.5x performance boost for both language identification and speech recognition models. Disabled quantization by default because it takes about 30 minutes (on my machine).

### CODE REVIEW

**Review by MaximProshin — COMMENTED** [review]
LGTM, just a few minor suggestion. On my laptop I got the following results:
LID model footprint reduction: 1.994
ASR model footprint reduction: 1.993
Language identification performance speedup: 2.382
Language transcription performance speedup:  2.414
Transcription word accuracy. FP32: 85.01%. INT8: 84.76%. Accuracy drop :0.25%.

**Review by eaidova — APPROVED** [review]

**Comment by nikita-savelyevv** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1380/discussion/#comment-1761899636'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nikita-savelyevv** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1380/discussion/#comment-1761899623'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nikita-savelyevv** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1380/discussion/#comment-1761899610'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nikita-savelyevv** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1380/discussion/#comment-1764077259'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by l-bat — APPROVED** [review]

**Pull request merged**
