### PR TITLE
Change NMS From x1y1x2y2 to x1y1wh Bug Fix

### PR DESCRIPTION
**Pull request by thavens**
[fixed example](https://www.youtube.com/watch?v=ahIKHIdzv9Y)
The white box is what the NMS used to see. Basically, it interpreted x2y2 as the width and height. So formula for the interpreted x2y2 is 2 * x1y1 + wh. 
You can see from the video that the boxes only disappear when the blue lines touch rather than when the white lines touch when nms_threthold = 0.

### CODE REVIEW

**Review by adrianboguszewski — APPROVED** [review]
It's ok from my perspective. Of course, all CI jobs must pass.

**Comment by raymondlo84** [comment]
Looks good, and seems like you have too many blank lines in the doc, should be a simple fix it seems. And once that passed, it's ready to merge after @adrianboguszewski validated it.


Run nbqa flake8 --ignore=E1[2](https://github.com/openvinotoolkit/openvino_notebooks/runs/6097517339?check_suite_focus=true#step:12:2)4,E20[3](https://github.com/openvinotoolkit/openvino_notebooks/runs/6097517339?check_suite_focus=true#step:12:3),E231,E266,E[4](https://github.com/openvinotoolkit/openvino_notebooks/runs/6097517339?check_suite_focus=true#step:12:4)02,E[5](https://github.com/openvinotoolkit/openvino_notebooks/runs/6097517339?check_suite_focus=true#step:12:5)01,E703,F821,W503,W291,W293 --nbqa-exclude="(301.*)|(302.*)" notebooks
  nbqa flake8 --ignore=E124,E203,E231,E2[6](https://github.com/openvinotoolkit/openvino_notebooks/runs/6097517339?check_suite_focus=true#step:12:6)6,E402,E501,E[7](https://github.com/openvinotoolkit/openvino_notebooks/runs/6097517339?check_suite_focus=true#step:12:7)03,F[8](https://github.com/openvinotoolkit/openvino_notebooks/runs/6097517339?check_suite_focus=true#step:12:8)21,W503,W2[9](https://github.com/openvinotoolkit/openvino_notebooks/runs/6097517339?check_suite_focus=true#step:12:9)1,W293 --nbqa-exclude="(301.*)|(302.*)" notebooks
  shell: /usr/bin/bash -e {0}
  env:
    PIP_CACHE_KEY: cache-pip-2022.1.0
    FILES_CACHE_KEY: files-cache-2022-03-23
    USER_CACHE_KEY: user-cache-2022-03-23
    HUB_HOME: /tmp/paddlehub
    pythonLocation: /opt/hostedtoolcache/Python/3.8.[12](https://github.com/openvinotoolkit/openvino_notebooks/runs/6097517339?check_suite_focus=true#step:12:12)/x64
notebooks/401-object-detection-webcam/401-object-detection.ipynb:cell_7:0:1: E303 too many blank lines (3)
notebooks/401-object-detection-webcam/401-object-detection.ipynb:cell_7:2:1: E302 expected 2 blank lines, found 3
Error: Process completed with exit code 1.

**Comment by thavens** [comment]
Just for curiosity. How do you guys use the formatter? Do you do it like the contributing guide? I had some version issue with the Jupiter lab extension and the formatter, so I got the formatter on vscode. Vscode notebooks are super buggy though and black seems to put newlines at the end of each cell which causes E303 (too many blank lines).
Right now I have to switch back and forth and install nbqa to make sure it's right.

**Review by ryanloney — APPROVED** [review]

**Comment by adrianboguszewski** [comment]
Thanks @thavens for the fix! I personally don't use any formatter. I format the code myself and then check with nbqa. After some time you have almost no issues :)

**Pull request merged**
