### PR TITLE
Update patch_notebooks.py to include 'openvino'

### PR DESCRIPTION
**Pull request by wkobielx**
I believe we are missing removing `openvino` from notebooks while patching, what leads  to uninstalling openvino during tests:

example on `test_llm-agent-langchain.ipynb` after patching:
image

This leads to next tests failing due to missing `openvino` package.

### CODE REVIEW

**Comment by wkobielx** [comment]
After fix:
image

**Comment by wkobielx** [comment]
@eaidova can you take a look?

**Comment by aleksandr-mokrov** [comment]
@wkobielx, this fix also affects nncf (git+https://github.com/openvinotoolkit/nncf.git). Looks like it should be a strict comparison `"openvino" == part`

**Comment by wkobielx** [comment]
@aleksandr-mokrov updated

**Comment by wkobielx** [comment]
image
image
image

few examples, seems it is not affecting nncf repo anymore

**Comment by wkobielx** [comment]
@aleksandr-mokrov @yatarkan can you take a look? There is a high chance that a lot of tests will fail with missing `openvino` package on next nightly run without this fix

**Review by yatarkan — APPROVED** [review]

**Pull request merged**
