### PR TITLE
Change Tensorflow notebook to train for 5 instead of 15 epochs

### PR DESCRIPTION
**Pull request by helena-intel**
This decreases the time it takes to run this notebook (also in the CI).
Added message that user can increase the number of epoch for better results.
Result on demo image is still correct.

### CODE REVIEW

**Comment by raymondlo84** [comment]
I would go with at least 10 to show the training is getting less of a diminishing return. 

Also, you are right we need to install 'curl' or the last part will fail with Ubuntu.

**Comment by ryanloney** [comment]
> I would go with maybe 7-8 to show the training is getting less of a diminishing return.
> 
> Also, you are right we need to install 'curl' or the last part will fail with Ubuntu. I saw the error just now on Ubuntu.

Can we change this to not use curl? 
```
output = subprocess.check_output(f"curl {inp_img_url} --output {inp_file_name}", shell=True)
```

**Review by ryanloney — APPROVED** [review]

**Comment by raymondlo84** [comment]
output = subprocess.check_output(f"curl {inp_img_url} --output {inp_file_name}", shell=True)
 

Yes, what's the alternative that you love the most?

**Comment by ryanloney** [comment]
> output = subprocess.check_output(f"curl {inp_img_url} --output {inp_file_name}", shell=True)
> 
> Yes, what's the alternative that you love the most?

Helena used urllib in monodepth notebook. Can we use that? https://docs.python.org/3/library/urllib.html

**Comment by helena-intel** [comment]
> Helena used urllib in monodepth notebook. Can we use that? https://docs.python.org/3/library/urllib.html

I'll make some standard functions that we can use across notebooks this week. This notebook is only in the develop branch now, so this is not urgent to fix in my opinion.

**Comment by helena-intel** [comment]
I changed it to five epochs because this is a 100-series notebook that should run relatively quickly on all computers (and the CI...). But we discussed to move this notebook to a different series, for which we can run different tests. With that change, I think it is better to keep the number of epochs at 15 and have the TensorFlow part exactly the same as the TensorFlow notebook. We can than also uncomment the early training part (that is part of the tutorial flow).

**Comment by raymondlo84** [comment]
Yes, let's move these out of the '1 series' I wonder how level 40 would look like now... Are we going to launch a rocket to Mars with AI?

**Comment by helena-intel** [comment]
Closing this PR in favor of keeping the number of epochs and changing the name. In a future PR we will not test this complete notebook in the CI.

**Pull request closed without merging**
