### PR TITLE
Add NNCF quantization for InstructPix2Pix notebook

### PR DESCRIPTION
**Pull request by l-bat**
Add post-training optimization support by NNCF for UNet model from [231-instruct-pix2pix-image-editing.ipynb](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/231-instruct-pix2pix-image-editing/231-instruct-pix2pix-image-editing.ipynb)

### CODE REVIEW

**Comment by l-bat** [comment]
<p>added</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1356/discussion/#comment-1744382579'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by l-bat** [comment]
<p>fixed</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1356/discussion/#comment-1744382602'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by l-bat** [comment]
<p>fixed</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1356/discussion/#comment-1744382625'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by l-bat** [comment]
<p>Aligned with README</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1356/discussion/#comment-1744382547'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by l-bat** [comment]
@nikita-savelyevv , @eaidova please take a look

**Comment by l-bat** [comment]
<p>I use probability to select intermediate inputs in the diffusion process. It is not related to dataset shuffling.</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1356/discussion/#comment-1746737316'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by l-bat** [comment]
<p>deleted</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1356/discussion/#comment-1746737343'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by l-bat** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1356/discussion/#comment-1746737379'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by l-bat** [comment]
<p>changed</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1356/discussion/#comment-1746195792'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by l-bat** [comment]
<p>fixed in <code>collect_calibration_data</code></p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1356/discussion/#comment-1746737409'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by nikita-savelyevv — APPROVED** [review]

**Review by eaidova — APPROVED** [review]

**Comment by l-bat** [comment]
> @l-bat , have you fixed the problem with SQ that I reported?

Yes

**Comment by eaidova** [comment]
@MaximProshin @l-bat  can I merge this notebook?

**Pull request merged**
