### PR TITLE
BERT POT Quantization Notebook

### PR DESCRIPTION
**Pull request by helena-intel**
Contributed by @AlexKoff88 at https://colab.research.google.com/drive/1rsWabKbkicFsuWErja0toQ8VMNHoJXTZ#scrollTo=PiAvrwo0tr6Z

### CODE REVIEW

**Comment by AlexKoff88** [comment]
Actually, the work has been done by @KodiaqQ. Please review as well.

**Comment by helena-intel** [comment]
Thanks @KodiaqQ ! This is a very welcome addition. I made some minor modifications and added the requirements to Pipfile/Pipfile.lock for the Docker image. If you want, feel free to make a new PR under your name with this code so it is clear that you authored it.

**Comment by ryanloney** [comment]
> Thanks @KodiaqQ ! This is a very welcome addition. I made some minor modifications and added the requirements to Pipfile/Pipfile.lock for the Docker image. If you want, feel free to make a new PR under your name with this code so it is clear that you authored it.

@raymondlo84 and I tried the notebook, it works locally. @KodiaqQ can you confirm that it works as intended? Step 10 is great, but it is not trivial for a user to understand that the model actually works just by seeing accuracy metric and benchmark with FPS. Can we add a step at the end with one input and one output? We mention Microsoft Research Paraphrase Corpus at the beginning of the notebook, but we provide no example using the corpus. 

Developers may be asking: 
* How do I use this model? 
* What is the expected input(s) and output(s)
* How do I use the quantized model `quantized_bert_mrpc.xml` with Inference Engine API

Step 11 should answer ^^ these questions with code. 

For reference, here is the benchmark result on my 9th Gen Core i7 CPU. Impressive speedup. 

FP16 version:
image

INT8 version:
image

**Comment by ryanloney** [comment]
Also, if it is easier, we can merge the PR and @KodiaqQ can fork the repo and make changes/enhancements. Let me know if that works.

**Review by KodiaqQ — APPROVED** [review]

**Comment by helena-intel** [comment]
@ryanloney See email thread. To me it is okay to merge now and add an inference demo later. It is not trivial to add a clear inference demo to this and the simplicity of this notebook is also nice.

**Review by ryanloney — APPROVED** [review]
Approving and merging, we will make enhancements (inference demo step) after merge

**Pull request merged**
