### PR TITLE
[GSoC] 236 - Question Answering

### PR DESCRIPTION
**Pull request by fajemila**
This PR is part of the prerequisite task for GSoC'23.
It demonstrates how to convert and use the [DistillBERT](https://huggingface.co/distilbert-base-cased-distilled-squad) model for question Answering with OpenVINO.

### CODE REVIEW

**Comment by adrianboguszewski** [comment]
Thank you for your contribution. Before we do the review please do the self-check first (tick the item when it's done):
- [ ] each function is described by docstrings and type hints
- [ ] notebook contains explicit descriptions and explanatory diagrams
- [ ] there is a README.md file in consistent style (look at other notebooks)
- [ ] the notebook is added to the main README and notebooks/README files
- [ ] there are no grammar, interpunctions or typo issues (use any free tool for that e.g. Grammarly)
- [ ] there are no committed files besides notebook and readme (please use images or videos from data dir)
- [ ] all CI checks passed

We will review only if all the above items are checked.

**Comment by fajemila** [comment]
> Thank you for your contribution. Before we do the review please do the self-check first (tick the item when it's done):
> 
> * [ ]  each function is described by docstrings and type hints
> * [ ]  notebook contains explicit descriptions and explanatory diagrams
> * [ ]  there is a README.md file in consistent style (look at other notebooks)
> * [ ]  the notebook is added to the main README and notebooks/README files
> * [ ]  there are no grammar, interpunctions or typo issues (use any free tool for that e.g. Grammarly)
> * [ ]  there are no committed files besides notebook and readme (please use images or videos from data dir)
> * [ ]  all CI checks passed
> 
> We will review only if all the above items are checked.

Thank you, I will update my repo with the changes to be made

**Comment by adrianboguszewski** [comment]
Thank you, we will review it when we have some resources. Please note we're reviewing in FIFO style.

**Comment by adrianboguszewski** [comment]
No worries if not related to your changes. We will fix it in another PR.

**Comment by fajemila** [comment]
> No worries if not related to your changes. We will fix it in another PR.

Thank you, @adrianboguszewski  How do I get in touch to discuss my application with the mentors?

**Comment by fajemila** [comment]
> > > No worries if not related to your changes. We will fix it in another PR.
> > 
> > 
> > Thank you, @adrianboguszewski How do I get in touch to discuss my application with the mentors?
> 
> It depends on the project. What project are we talking about?

Okay, I'm interested in the smart meeting notes project

**Comment by fajemila** [comment]
> So @eaidova and @andrei-kochin can help :)

Okay thank you

**Comment by fajemila** [comment]
@andrei-kochin hi, how do I get across to you concerning my proposal?

**Comment by eaidova** [comment]
> @andrei-kochin hi, how do I get across to you concerning my proposal? @eaidova hi, I have not been able to get a reply from you, I have mailed you as regards my proposal

ksorry for that, looks like it went to spam due to some reasons, I reviewed, everything is fine, you can submit

**Comment by raymondlo84** [comment]
We need to a few proof read, but overall looks clean.

However once you have installed the requirements.txt file you dont need to run the above line
-->
=) Lots of typos for example.

**Comment by fajemila** [comment]
> We need to a few proof read, but overall looks clean.
> 
> e.g.,
> 
> ```
> However once you have installed the requirements.txt file you dont need to run the above line
> ```

okay, i will correct them

**Review by adrianboguszewski — CHANGES_REQUESTED** [review]
Please:
- move your notebook to 213-question-answering directory
- rename the 213-question-answering to 213-bert-question-answering
- use OpenVINO model inside answer_question function. Now, you're using the Pytorch model
- use Grammarly or any other tool to fix grammar, typos and punctuations

**Comment by fajemila** [comment]
Hi, please, i unknowingly closed this pull request, can i get it reopened pls. thanks

**Comment by adrianboguszewski** [comment]
I cannot reopen this. The option is disabled. Please open a new PR or follow these instructions: https://gist.github.com/robertpainsi/2c42c15f1ce6dab03a0675348edd4e2c

**Comment by fajemila** [comment]
> * use OpenVINO model inside answer_question function. Now, you're using the Pytorch model

Hi, I don't quite get this line, when I called the answer_function at the last cell of the notebook, I used the infer_request variable class which is already compiled into the OpenVINO model IR

**Comment by fajemila** [comment]
> I cannot reopen this. The option is disabled. Please open a new PR or follow these instructions: https://gist.github.com/robertpainsi/2c42c15f1ce6dab03a0675348edd4e2c

thank you, I tried to follow the link but I didn't have luck with it, I will be opening a new PR

**Comment by fajemila** [comment]
> > > * use OpenVINO model inside answer_question function. Now, you're using the Pytorch model
> > 
> > 
> > Hi, I don't quite get this line, when I called the answer_function at the last cell of the notebook, I used the infer_request variable class which is already compiled into the OpenVINO model IR
> 
> You need to reopen the PR so I am able to comment on this. I cannot see any changes now.

link to my new PR here https://github.com/openvinotoolkit/openvino_notebooks/pull/1022

i have moved the notebook to 213-question-answering directory and changed the name to 213-bert-question-answering

**Pull request closed without merging**
