### PR TITLE
Move stable-diffusion-text-to-image to optimum intel

### PR DESCRIPTION
**Pull request by sbalandi**
Task:
- *[CVS-143643](https://jira.devtools.intel.com/browse/CVS-143643)*

### CODE REVIEW

**Comment by sbalandi** [comment]
<p>removed</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2107/discussion/#comment-2165055214'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sbalandi** [comment]
<p>removed</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2107/discussion/#comment-2165055245'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sbalandi** [comment]
<p>added removing of pipeline</p><p>separated demos</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2107/discussion/#comment-2165055287'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sbalandi** [comment]
<p>added seed with np.random.seed() like here <a href="https://huggingface.co/docs/optimum/intel/inference#diffusers-models" target="_blank">https://huggingface.co/docs/optimum/intel/inference#diffusers-models</a></p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2107/discussion/#comment-2165055317'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sbalandi** [comment]
<p>yes, looks like it's required, inference fails without preprocessing with: </p><p><code>RuntimeError: Exception from src/inference/src/cpp/infer_request.cpp:223:</code></p><p><code>Exception from src/plugins/intel_cpu/src/node.cpp:1626:</code></p><p><code>Shape inference of Concat node with name __module.up_blocks.1/aten::cat/Concat failed: Check 'TRShape::merge_into(output_shape, in_copy)' failed at src/core/shape_inference/include/concat_shape_inference.hpp:43:</code></p><p><code>While validating node 'opset1::Concat __module.up_blocks.1/aten::cat/Concat (opset1::Add __module.up_blocks.0.upsamplers.0.conv/aten::_convolution/Add[0]:f32[?,1280,2..,2..], opset1::Add __module.down_blocks.2.attentions.1/aten::add/Add[0]:f32[?,1280,1..,1..]) -&gt; (f32[?,2560,2..,2..])' with friendly_name '__module.up_blocks.1/aten::cat/Concat':</code></p><p><code>Shape inference input shapes {{2,1280,18,26},{2,1280,18,25}}</code></p><p><code>Argument shapes are inconsistent; they must have the same rank, and must have equal dimension everywhere except on the concatenation axis (axis 1).</code></p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2107/discussion/#comment-2165055351'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sbalandi** [comment]
<p>removed</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2107/discussion/#comment-2165055415'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by eaidova** [comment]
@sbalandi could you please also apply code formatting with black for updated notebook?
https://github.com/openvinotoolkit/openvino_notebooks/blob/latest/CONTRIBUTING.md#black-automatic-code-formatter

**Comment by sbalandi** [comment]
<p>removed</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2107/discussion/#comment-2166295020'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sbalandi** [comment]
<p>fixed</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2107/discussion/#comment-2166295070'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sbalandi** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2107/discussion/#comment-2166306058'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sbalandi** [comment]
<p>added</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2107/discussion/#comment-2166295130'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sbalandi** [comment]
<p>removed</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2107/discussion/#comment-2166295191'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sbalandi** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2107/discussion/#comment-2166478812'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sbalandi** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2107/discussion/#comment-2166514342'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by eaidova — APPROVED** [review]

**Review by aleksandr-mokrov — APPROVED** [review]

**Comment by eaidova** [comment]
@sbalandi please fix formatting and I'll merge

**Pull request merged**
