### PR TITLE
[GSOC] Added DETR resnet50 notebook

### PR DESCRIPTION
**Pull request by Tatwansh**
This notebook is done as the prerequisite of GSoc'23.
It uses the DETR res-50 model with OpenVino and quick inference with CPU.

I was assigned this task at https://github.com/openvinotoolkit/openvino_notebooks/issues/832.

### CODE REVIEW

**Comment by adrianboguszewski** [comment]
Thank you for your contribution. Before we do the review please do the self-check first (tick the item when it's done):
- [ ] each function is described by docstrings and type hints
- [ ] notebook contains explicit descriptions and explanatory diagrams
- [ ] the notebook doesn't use any data (image, video, etc.) that is not CC4.0 licensed 
- [ ] there is a README.md file in consistent style (look at other notebooks)
- [ ] the notebook is added to the main README
- [ ] there are no grammar, punctuation or typo issues (use any free tool for that e.g. Grammarly)
- [ ] there are no committed files besides notebook and readme (please use images or videos from data dir)
- [ ] your PR doesn't change any other notebooks
- [ ] all CI checks passed

**Comment by Tatwansh** [comment]
>Progress Update: 
> * [x]  each function is described by docstrings and type hints
> * [ ]  notebook contains explicit descriptions and explanatory diagrams
> * [x]  the notebook doesn't use any data (image, video, etc.) that is not CC4.0 licensed
> * [x]  there is a README.md file in consistent style (look at other notebooks)
> * [x]  the notebook is added to the main README
> * [x]  there are no grammar, punctuation or typo issues (use any free tool for that e.g. Grammarly)
> * [x]  there are no committed files besides notebook and readme (please use images or videos from data dir)
> * [x]  your PR doesn't change any other notebooks
> * [ ]  all CI checks passed

**Comment by raymondlo84** [comment]
```
help(th.onnx.export) # function used to conert model to its onnx couterpart
```
There are lots of print statement, and would be good to consolidate them.

The install should happen at the top. FYI. 

I worry these will conflict with other notebooks. Why are these necessary? 
```
!pip install -Iv protobuf==3.20.2
!pip install onnxruntime
!pip install onnx
```
Also, we should type up the headings with explanations and proper references.

**Comment by adrianboguszewski** [comment]
Closing due to inactivity in the last 2 weeks

**Pull request closed without merging**
