### PR TITLE
Fixed reshape array Quantized model

### PR DESCRIPTION
**Pull request by AnishaUdayakumar**
The reshape function for quantized_det_compiled_model is expecting a tuple or a list to specify the new shape of the array (otherwise is fails for GPU | AUTO)

### CODE REVIEW

**Comment by AnishaUdayakumar** [comment]
<p>Yes I will revert back them</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1191/discussion/#comment-1635859346'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AnishaUdayakumar** [comment]
<p>We get an error when we set it to device != "GPU":</p><p>If that wouldn't cause any issue then I guess this fix will not be needed.</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1191/discussion/#comment-1635859328'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AnishaUdayakumar** [comment]
<p>Reverted back all the cell outputs.</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1191/discussion/#comment-1635859346'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by eaidova** [comment]
@AnishaUdayakumar, thanks, but it is not applicable anymore. Can I close your PR?

**Comment by AnishaUdayakumar** [comment]
> @AnishaUdayakumar, thanks, but it is not applicable anymore. Can I close your PR?

Sure.

**Pull request closed without merging**
