### PR TITLE
[GSoC] yolov5-blazeface notebook updated with explanations. 

### PR DESCRIPTION
**Pull request by AnuragTimilsina**
This pull request is made for the partial fulfilment of the GSOC prerequisite task. The yolov5-blaze face notebook was updated with explanations and some modifications. I have tried my best to meet the community guidelines.

### CODE REVIEW

**Comment by adrianboguszewski** [comment]
Thank you for your contribution. Before we do the review please do the self-check first (copy the list and tick the item when it's done):
- [ ] each function is described by docstrings and type hints
- [ ] notebook contains explicit descriptions and explanatory diagrams
- [ ] the notebook doesn't use any data (image, video, etc.) that is not CC4.0 licensed 
- [ ] there is a README.md file in consistent style (look at other notebooks)
- [ ] the notebook is added to the main README
- [ ] there are no grammar, punctuation or typo issues (use any free tool for that e.g. Grammarly)
- [ ] there are no committed files besides notebook and readme (please use images or videos from data dir)
- [ ] your PR doesn't change any other notebooks
- [ ] all CI checks passed

**Comment by AnuragTimilsina** [comment]
Hello, thank you for the response. I have ensured that all of the criteria are met. However, in the CI check, docker_treon/build_docker is cancelled after 360 mins of trying. What might be the reason for that?

[ ] -  each function is described by docstrings and type hints (Done)
[ ] -  notebook contains explicit descriptions and explanatory diagrams (Done)
[ ] -  the notebook doesn't use any data (image, video, etc.) that is not CC4.0 licensed (Done)
[ ] -  there is a README.md file in consistent style (look at other notebooks) (Done)
[ ] -  the notebook is added to the main README (Done)
[ ] -  there are no grammar, punctuation or typo issues (use any free tool for that e.g. Grammarly) (Done)
[ ] -  there are no committed files besides notebook and readme (please use images or videos from data dir) (Done)
[ ] -  your PR doesn't change any other notebooks (Done)
[ ] -  all CI checks passed (The docker_treon check is cancelled)

**Comment by adrianboguszewski** [comment]
Please verify your PR. It doesn't contain any new notebook. Update this PR, and don't create a new one if you already provided this URL in your GSoC application. Please do it ASAP, as the deadline has passed.

**Comment by AnuragTimilsina** [comment]
image

The test case for my new notebook is passed. However, the test case seems to fail in this step. I haven't added any new notebooks or changed anything in my fork of the repo besides my own notebook (205-vision_background_removal). 

The error log was as follows:
image

**Comment by raymondlo84** [comment]
u2net_lite = model_config(
    name="u2net_lite",
    url="https://drive.google.com/uc?id=1rbSTGKAE-MTxBYHd-51l2hMOQPT_7EPy",
    model=U2NETP,
    model_args=(),
)
u2net = model_config(
    name="u2net",
    url="https://drive.google.com/uc?id=1ao1ovG1Qtx4b7EoskHXmi2E9rp5CHLcZ",
    model=U2NET,
    model_args=(3, 1),
)
u2net_human_seg = model_config(
    name="u2net_human_seg",
    url="https://drive.google.com/uc?id=1-Yg0cxgrNhHP-016FPdp902BR-kSsA4P",
    model=U2NET,
    model_args=(3, 1),
)

Is that all the changes?

**Comment by AnuragTimilsina** [comment]
@raymondlo84 The task required a detailed notebook tutorial to run and optimize the U2-net model using the OpenVino toolkit (as mentioned in the prerequisite task section). These are the changes I made:  https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/984/

**Comment by adrianboguszewski** [comment]
It was supposed to be a new notebook with a U2 model. I'm closing this, but if you want to create a new notebook, feel free to open a new PR.

**Comment by AnuragTimilsina** [comment]
Sure. I'll create a new one.

**Pull request closed without merging**
