### PR TITLE
nbval: restore macOS, upgrade pip

### PR DESCRIPTION
**Pull request by helena-intel**
- put macOS back in nbval (temporarily removed in #484 )
- upgrade pip to latest version.

We pinned pip to 21.3 because of issues with 22.* in (#392 ). The latest pip version works for me locally now. If this PR passes CI, the installation guides in the Wiki should be updated too.

### CODE REVIEW

**Review by ryanloney — APPROVED** [review]

**Comment by ryanloney** [comment]
Merging this without additional review, since it impacts only the CI and tests passing.

**Comment by raymondlo84** [comment]
Thanks Helena!!

**Comment by helena-intel** [comment]
After merging to main, this PR fails CI for macOS because 107 takes too long to run there. Is it possible to patch that notebook to speed it up in CI? https://github.com/openvinotoolkit/openvino_notebooks/wiki/Notebooks-Development---CI-Test-Speedup

**Comment by raymondlo84** [comment]
it seems to be broken :\ image
image

**Comment by Debskij** [comment]
Hi @helena-intel, thanks for this contribution. Due to performance issues I had created similar PR with ignoring some notebooks (https://github.com/openvinotoolkit/openvino_notebooks/pull/545). Feel free to close this one.

**Pull request closed without merging**
