### PR TITLE
Fix tensorflow notebook issue

### PR DESCRIPTION
**Pull request by helena-intel**
Pin Pillow to 8.2 to fix issue with Tensorflow Flowers notebook.

### CODE REVIEW

**Comment by helena-intel** [comment]
@raymondlo84 can you check if this fixes #144 ?

**Comment by raymondlo84** [comment]
Wow... How can you find that so quickly... gosh. Yes, it works now! ... and how how how how how.... 👍

**Review by raymondlo84 — APPROVED** [review]
Validated the fix. Will go through CI next.

**Comment by helena-intel** [comment]
> Wow... How can you find that so quickly... gosh. Yes, it works now! ... and how how how how how.... 👍

I wish I could take credit but I figured if a dependency suddenly breaks other people will have run into it and hopefully found a fix and they did. see https://github.com/python-pillow/Pillow/issues/5571
I pinned Pillow to 8.2.* now because I wanted to fix this with a known good version. I'll change it to <8.3 or !=8.3.0 later.

**Pull request merged**
