### PR TITLE
216-image-inpainting-gmcnn Jupyter notebook tutorial

### PR DESCRIPTION
**Pull request by Chamodya-ka**
Pipeline

This notebook consist of a tutorial on image inpainting using GMCNN model from public open model zoo.
This notebook implements the above pipeline.

### CODE REVIEW

**Comment by adrianboguszewski** [comment]
@Chamodya-ka when it's ready, please change status from "draft" to "ready"

**Comment by Chamodya-ka** [comment]
Sure will do once I pass the checks.

**Comment by adrianboguszewski** [comment]
They probably won't run until this is draft only.

**Comment by paularamo** [comment]
@Chamodya-ka please follow this guideline to make the update to OpenVINO 2.0 API

https://docs.openvino.ai/latest/openvino_2_0_transition_guide.html

**Pull request closed without merging**
