### PR TITLE
[CI] Add PR labeler

### PR DESCRIPTION
**Pull request by akashchi**
PRs will be labeled with an [automatic regexp-based labeler](https://github.com/github/issue-labeler) and a [changed-files-based one](https://github.com/doka-guide/doka-labeler/blob/main/examples/content-based.yml).

The `labeler_regexp.yml` and `labeler_files.yml` files under the `.github/labeler` folder contain the mapping between labels and associated regular expressions and changed files. 

1. If the PR's title and/or description match the regular expression, a label is added to the PR.
2. If the PR's changed files match the provided paths, a label is added to the PR.

### CODE REVIEW

**Comment by adrianboguszewski** [comment]
@akashchi I worry this is a too simple solution. I'd expect something like checking if:
- the notebook hasn't existed before - "new notebook"
- the existing notebook changed - "improvement"
- any of the readme files changed - "documentation"
- gsoc in the title/description - "gsoc"

We have to check for real changes in most cases instead of titles/descriptions. I hope you can design the rules like these above.

**Review by adrianboguszewski — CHANGES_REQUESTED** [review]
See the comment above

**Comment by akashchi** [comment]
> See the comment above

I have added rules for labeling based on the changed files.

**Review by adrianboguszewski — APPROVED** [review]
LGTM

**Pull request merged**
